package chainrepublik.kernel.net_stat.tables;

import chainrepublik.kernel.UTILS;
import chainrepublik.kernel.net_stat.CTable;

public class CComProds extends CTable
{
    public CComProds() 
    {
        // Constructor
        super("com_prods");
    }
    
    public void create() throws Exception
    {
        if (!this.tableExist("com_prods"))
        {
            // Status
            System.out.print("Creating table com_prods...");
            
            // Create
            UTILS.DB.executeUpdate("CREATE TABLE com_prods (ID BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY, "
                                                         + "com_type VARCHAR(50) NOT NULL DEFAULT '', "
                                                         + "prod VARCHAR(50) NOT NULL DEFAULT '', "
                                                         + "type VARCHAR(25) NOT NULL DEFAULT '', "
                                                         + "buy_split VARCHAR(10) NOT NULL DEFAULT '')");
            
            // Indexes
            UTILS.DB.executeUpdate("CREATE INDEX com_prods_com_type ON com_prods(com_type)");
            UTILS.DB.executeUpdate("CREATE INDEX com_prods_prod ON com_prods(prod)");
            UTILS.DB.executeUpdate("CREATE INDEX com_prods_type ON com_prods(type)");
            UTILS.DB.executeUpdate("CREATE INDEX com_prods_buy_split ON com_prods(buy_split)");
            UTILS.DB.executeUpdate("CREATE UNIQUE INDEX com_prods_com_type_prod ON com_prods(com_type, prod)");
            
            // Populate
            if (!this.reorg)
               this.populate();
            
            // Confirm
            System.out.println("Done.");
        }
    }
    
    public void populate() throws Exception
    {
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_OIL', prod='ID_ELECTRICITY', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_OIL', prod='ID_LIC_PROD_OIL', type='ID_LIC_PROD', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_OIL', prod='ID_OIL', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_OIL', prod='ID_TOOLS_PROD_OIL', type='ID_TOOLS', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_ELECTRICITY', prod='ID_ELECTRICITY', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_ELECTRICITY', prod='ID_LIC_PROD_ELECTRICITY', type='ID_LIC_PROD', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_ELECTRICITY', prod='ID_TOOLS_PROD_ELECTRICITY', type='ID_TOOLS', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_ELECTRICITY', prod='ID_BUILD_COM_ELECTRICITY', type='ID_BUILDING', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_OIL', prod='ID_BUILD_COM_OIL', type='ID_BUILDING', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_GAS', prod='ID_ELECTRICITY', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_GAS', prod='ID_OIL', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_GAS', prod='ID_GAS', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_GAS', prod='ID_BUILD_COM_GAS', type='ID_BUILDING', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_GAS', prod='ID_TOOLS_PROD_GAS', type='ID_TOOLS', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_WOOD', prod='ID_ELECTRICITY', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_WOOD', prod='ID_OIL', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_WOOD', prod='ID_GAS', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_WOOD', prod='ID_WOOD', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_WOOD', prod='ID_BUILD_COM_WOOD', type='ID_BUILDING', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_WOOD', prod='ID_TOOLS_PROD_WOOD', type='ID_TOOLS', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_IRON', prod='ID_ELECTRICITY', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_IRON', prod='ID_OIL', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_IRON', prod='ID_GAS', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_IRON', prod='ID_IRON', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_IRON', prod='ID_BUILD_COM_IRON_MINE', type='ID_BUILDING', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_IRON', prod='ID_TOOLS_PROD_IRON', type='ID_TOOLS', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_COTTON', prod='ID_ELECTRICITY', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_COTTON', prod='ID_OIL', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_COTTON', prod='ID_WOOD', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_COTTON', prod='ID_COTTON', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_COTTON', prod='ID_BUILD_COM_COTTON', type='ID_BUILDING', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_SAND', prod='ID_ELECTRICITY', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_SAND', prod='ID_OIL', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_SAND', prod='ID_GAS', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_SAND', prod='ID_SAND', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_SAND', prod='ID_BUILD_COM_SAND', type='ID_BUILDING', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_SAND', prod='ID_TOOLS_PROD_SAND', type='ID_TOOLS', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_WHEAT', prod='ID_OIL', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_WHEAT', prod='ID_WHEAT', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_WHEAT', prod='ID_BUILD_COM_WHEAT', type='ID_BUILDING', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_WHEAT', prod='ID_TOOLS_PROD_WHEAT', type='ID_TOOLS', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_COTTON', prod='ID_TOOLS_PROD_COTTON', type='ID_TOOLS', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_FARM', prod='ID_ELECTRICITY', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_FARM', prod='ID_OIL', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_FARM', prod='ID_EGG', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_FARM', prod='ID_LEATHER', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_FARM', prod='ID_MEAT', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_FARM', prod='ID_MILK', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_FARM', prod='ID_BUILD_COM_FARM', type='ID_BUILDING', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_FARM', prod='ID_TOOLS_PROD_FARM', type='ID_TOOLS', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_GRAPES', prod='ID_ELECTRICITY', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_GRAPES', prod='ID_OIL', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_GRAPES', prod='ID_GRAPES', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_GRAPES', prod='ID_BUILD_COM_GRAPES', type='ID_BUILDING', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_GRAPES', prod='ID_TOOLS_PROD_GRAPES', type='ID_TOOLS', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CLAY', prod='ID_ELECTRICITY', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CLAY', prod='ID_OIL', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CLAY', prod='ID_GAS', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CLAY', prod='ID_CLAY', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CLAY', prod='ID_BUILD_COM_CLAY', type='ID_BUILDING', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CLAY', prod='ID_TOOLS_PROD_CLAY', type='ID_TOOLS', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_PLASTICS', prod='ID_ELECTRICITY', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_PLASTICS', prod='ID_OIL', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_PLASTICS', prod='ID_PLASTIC', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_PLASTICS', prod='ID_BUILD_COM_PLASTIC', type='ID_BUILDING', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_PLASTICS', prod='ID_TOOLS_PROD_PLASTIC', type='ID_TOOLS', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_PLASTICS', prod='ID_GAS', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_VEGETABLES', prod='ID_ELECTRICITY', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_VEGETABLES', prod='ID_OIL', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_VEGETABLES', prod='ID_TOMATO', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_VEGETABLES', prod='ID_OLIVES', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_VEGETABLES', prod='ID_LIME', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_VEGETABLES', prod='ID_PINEAPPLE', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_VEGETABLES', prod='ID_COCONUT', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_VEGETABLES', prod='ID_BUILD_COM_VEGS', type='ID_BUILDING', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_VEGETABLES', prod='ID_TOOLS_PROD_VEGS', type='ID_TOOLS', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_SUGARCANE', prod='ID_ELECTRICITY', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_SUGARCANE', prod='ID_OIL', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_SUGARCANE', prod='ID_SUGARCANE', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_SUGARCANE', prod='ID_BUILD_COM_SUGARCANE', type='ID_BUILDING', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_SUGARCANE', prod='ID_TOOLS_PROD_SUGARCANE', type='ID_TOOLS', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_SUGAR', prod='ID_ELECTRICITY', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_SUGAR', prod='ID_OIL', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_SUGAR', prod='ID_GAS', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_SUGAR', prod='ID_SUGARCANE', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_SUGAR', prod='ID_SUGAR', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_SUGAR', prod='ID_BUILD_COM_SUGAR', type='ID_BUILDING', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_SUGAR', prod='ID_TOOLS_PROD_SUGAR', type='ID_TOOLS', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_ALCOHOOL', prod='ID_ELECTRICITY', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_ALCOHOOL', prod='ID_GAS', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_ALCOHOOL', prod='ID_ALCOHOOL', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_ALCOHOOL', prod='ID_BUILD_COM_ALCOHOOL', type='ID_BUILDING', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_ALCOHOOL', prod='ID_TOOLS_PROD_ALCOHOOL', type='ID_TOOLS', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_FLOUR', prod='ID_ELECTRICITY', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_FLOUR', prod='ID_OIL', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_FLOUR', prod='ID_WHEAT', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_FLOUR', prod='ID_FLOUR', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_FLOUR', prod='ID_BUILD_COM_FLOUR', type='ID_BUILDING', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_FLOUR', prod='ID_TOOLS_PROD_FLOUR', type='ID_TOOLS', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_TUTUN', prod='ID_ELECTRICITY', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_TUTUN', prod='ID_OIL', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_TUTUN', prod='ID_GAS', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_TUTUN', prod='ID_TUTUN', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_TUTUN', prod='ID_BUILD_COM_TUTUN', type='ID_BUILDING', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_TUTUN', prod='ID_TOOLS_PROD_TUTUN', type='ID_TOOLS', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_AUTONOMOUS', prod='ID_ELECTRICITY', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_GLASS', prod='ID_GLASS', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_GLASS', prod='ID_BUILD_COM_GLASS', type='ID_BUILDING', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_GLASS', prod='ID_TOOLS_PROD_GLASS', type='ID_TOOLS', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_GLASS', prod='ID_SAND', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_GLASS', prod='ID_ELECTRICITY', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_GLASS', prod='ID_OIL', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_GLASS', prod='ID_GAS', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_BOTTLES', prod='ID_ELECTRICITY', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_BOTTLES', prod='ID_GAS', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_BOTTLES', prod='ID_GLASS', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_BOTTLES', prod='ID_BOTTLE', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_BOTTLES', prod='ID_BUILD_COM_BOTTLES', type='ID_BUILDING', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_BOTTLES', prod='ID_TOOLS_PROD_BOTTLES', type='ID_TOOLS', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_BREAD', prod='ID_ELECTRICITY', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_BREAD', prod='ID_GAS', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_BREAD', prod='ID_EGG', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_BREAD', prod='ID_MILK', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_BREAD', prod='ID_FLOUR', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_BREAD', prod='ID_BUILD_COM_BAKERY', type='ID_BUILDING', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_BREAD', prod='ID_TOOLS_PROD_BAKERY', type='ID_TOOLS', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_BREAD', prod='ID_BREAD', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_BRICKS', prod='ID_ELECTRICITY', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_BRICKS', prod='ID_GAS', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_BRICKS', prod='ID_OIL', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_BRICKS', prod='ID_CLAY', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_BRICKS', prod='ID_BRICK', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_BRICKS', prod='ID_BUILD_COM_BRICKS', type='ID_BUILDING', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_BRICKS', prod='ID_TOOLS_PROD_BRICKS', type='ID_TOOLS', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CEMENT', prod='ID_ELECTRICITY', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CEMENT', prod='ID_GAS', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CEMENT', prod='ID_OIL', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CEMENT', prod='ID_SAND', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CEMENT', prod='ID_CEMENT', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CEMENT', prod='ID_BUILD_COM_CEMENT', type='ID_BUILDING', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CEMENT', prod='ID_TOOLS_PROD_CEMENT', type='ID_TOOLS', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_DYNAMITE', prod='ID_ELECTRICITY', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_DYNAMITE', prod='ID_OIL', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_DYNAMITE', prod='ID_PAPER', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_DYNAMITE', prod='ID_DYNAMITE', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_DYNAMITE', prod='ID_BUILD_COM_DYNAMITE', type='ID_BUILDING', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_DYNAMITE', prod='ID_TOOLS_PROD_DYNAMITE', type='ID_TOOLS', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_PAPER', prod='ID_ELECTRICITY', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_PAPER', prod='ID_OIL', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_PAPER', prod='ID_GAS', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_PAPER', prod='ID_PAPER', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_PAPER', prod='ID_BUILD_COM_PAPER', type='ID_BUILDING', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_PAPER', prod='ID_TOOLS_PROD_PAPER', type='ID_TOOLS', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_PAPER', prod='ID_COTTON', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_TOOLS', prod='ID_ELECTRICITY', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_TOOLS', prod='ID_GAS', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_TOOLS', prod='ID_OIL', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_TOOLS', prod='ID_IRON', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_TOOLS', prod='ID_WOOD', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_TOOLS', prod='ID_PLASTIC', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_TOOLS', prod='ID_GLASS', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_MATERIAL', prod='ID_ELECTRICITY', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_MATERIAL', prod='ID_OIL', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_MATERIAL', prod='ID_COTTON', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_MATERIAL', prod='ID_MATERIAL', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_MATERIAL', prod='ID_BUILD_COM_MATERIAL', type='ID_BUILDING', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_MATERIAL', prod='ID_TOOLS_PROD_MATERIAL', type='ID_TOOLS', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_AMMUNITION', prod='ID_ELECTRICITY', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_AMMUNITION', prod='ID_OIL', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_AMMUNITION', prod='ID_GAS', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_AMMUNITION', prod='ID_IRON', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_AMMUNITION', prod='ID_GUNPOWDER', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_AMMUNITION', prod='ID_BULLETS_AKM', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_AMMUNITION', prod='ID_BULLETS_TANK', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_AMMUNITION', prod='ID_BULLET_PISTOL', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_AMMUNITION', prod='ID_BULLET_REVOLVER', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_AMMUNITION', prod='ID_BULLETS_SNIPER', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_AMMUNITION', prod='ID_BULLETS_SHOTGUN', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_AMMUNITION', prod='ID_BUILD_COM_AMMUNITION', type='ID_BUILDING', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_AMMUNITION', prod='ID_TOOLS_PROD_AMMUNITION', type='ID_TOOLS', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_WEAPONS', prod='ID_ELECTRICITY', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_WEAPONS', prod='ID_GAS', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_WEAPONS', prod='ID_OIL', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_WEAPONS', prod='ID_IRON', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_WEAPONS', prod='ID_WOOD', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_WEAPONS', prod='ID_PLASTIC', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_WEAPONS', prod='ID_GLASS', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_WEAPONS', prod='ID_BUILD_COM_WEAPONS', type='ID_BUILDING', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_WEAPONS', prod='ID_TOOLS_PROD_WEAPONS', type='ID_TOOLS', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_WEAPONS', prod='ID_PISTOL', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_WEAPONS', prod='ID_REVOLVER', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_WEAPONS', prod='ID_RPG', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_WEAPONS', prod='ID_MISSILE_HELLFIRE', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_WEAPONS', prod='ID_MISSILE_MGM_140', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_WEAPONS', prod='ID_MISSILE_BALLISTIC_SHORT', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_WEAPONS', prod='ID_MISSILE_BALLISTIC_MEDIUM', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_WEAPONS', prod='ID_CAR_Q1', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_WEAPONS', prod='ID_MISSILE_BALLISTIC_INTERCONTINENTAL', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_WEAPONS', prod='ID_TANK', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_WEAPONS', prod='ID_AKM', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_WEAPONS', prod='ID_HK416', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_WEAPONS', prod='ID_500MILLS', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_WEAPONS', prod='ID_M110', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_RESTAURANT', prod='ID_ELECTRICITY', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_RESTAURANT', prod='ID_GAS', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_RESTAURANT', prod='ID_EGG', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_RESTAURANT', prod='ID_FLOUR', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_RESTAURANT', prod='ID_MILK', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_RESTAURANT', prod='ID_MEAT', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_RESTAURANT', prod='ID_OLIVES', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_RESTAURANT', prod='ID_BREAD', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_RESTAURANT', prod='ID_CROISANT', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_RESTAURANT', prod='ID_HOT_DOG', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_RESTAURANT', prod='ID_PASTA', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_RESTAURANT', prod='ID_BURGER', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_RESTAURANT', prod='ID_BIG_BURGER', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_RESTAURANT', prod='ID_PIZZA', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_RESTAURANT', prod='ID_BUILD_COM_RESTAURANT', type='ID_BUILDING', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_RESTAURANT', prod='ID_TOOLS_PROD_RESTAURANT', type='ID_TOOLS', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CIGARS', prod='ID_ELECTRICITY', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CIGARS', prod='ID_GAS', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CIGARS', prod='ID_PAPER', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CIGARS', prod='ID_TUTUN', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CIGARS', prod='ID_CIG_CHURCHILL', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CIGARS', prod='ID_CIG_TORO', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CIGARS', prod='ID_CIG_TORPEDO', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CIGARS', prod='ID_CIG_PANATELA', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CIGARS', prod='ID_CIG_CORONA', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CIGARS', prod='ID_BUILD_COM_CIGARS', type='ID_BUILDING', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CIGARS', prod='ID_TOOLS_PROD_CIGARS', type='ID_TOOLS', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_BAR', prod='ID_ELECTRICITY', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_BAR', prod='ID_ALCOHOOL', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_BAR', prod='ID_SUGAR', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_BAR', prod='ID_LIME', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_BAR', prod='ID_TOMATO', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_BAR', prod='ID_PINEAPPLE', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_BAR', prod='ID_COCONUT', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_BAR', prod='ID_SAMPANIE', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_BAR', prod='ID_MARTINI', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_BAR', prod='ID_MOJITO', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_BAR', prod='ID_MARY', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_BAR', prod='ID_SINGAPORE', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_BAR', prod='ID_PINA', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_BAR', prod='ID_BUILD_COM_BAR', type='ID_BUILDING', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_BAR', prod='ID_TOOLS_PROD_BAR', type='ID_TOOLS', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_WINE', prod='ID_ELECTRICITY', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_WINE', prod='ID_OIL', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_WINE', prod='ID_GRAPES', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_WINE', prod='ID_BOTTLE', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_WINE', prod='ID_WINE', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_WINE', prod='ID_BUILD_COM_WINE', type='ID_BUILDING', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_WINE', prod='ID_TOOLS_PROD_WINE', type='ID_TOOLS', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CLOTHES', prod='ID_ELECTRICITY', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CLOTHES', prod='ID_OIL', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CLOTHES', prod='ID_MATERIAL', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CLOTHES', prod='ID_LEATHER', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CLOTHES', prod='ID_BUILD_COM_CLOTHES', type='ID_BUILDING', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CLOTHES', prod='ID_TOOLS_PROD_CLOTHES', type='ID_TOOLS', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CLOTHES', prod='ID_SOSETE_Q1', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CLOTHES', prod='ID_SOSETE_Q2', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CLOTHES', prod='ID_SOSETE_Q3', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CLOTHES', prod='ID_CAMASA_Q1', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CLOTHES', prod='ID_CAMASA_Q2', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CLOTHES', prod='ID_CAMASA_Q3', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CLOTHES', prod='ID_GHETE_Q1', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CLOTHES', prod='ID_GHETE_Q2', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CLOTHES', prod='ID_GHETE_Q3', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CLOTHES', prod='ID_PANTALONI_Q1', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CLOTHES', prod='ID_PANTALONI_Q2', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CLOTHES', prod='ID_PANTALONI_Q3', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CLOTHES', prod='ID_PULOVER_Q1', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CLOTHES', prod='ID_PULOVER_Q2', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CLOTHES', prod='ID_PULOVER_Q3', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CLOTHES', prod='ID_PALTON_Q1', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CLOTHES', prod='ID_PALTON_Q2', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CLOTHES', prod='ID_PALTON_Q3', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_JEWELRY', prod='ID_ELECTRICITY', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_JEWELRY', prod='ID_GAS', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_JEWELRY', prod='ID_SILVER', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_JEWELRY', prod='ID_GOLD', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_JEWELRY', prod='ID_PLATINUM', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_JEWELRY', prod='ID_BRATARA_Q1', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_JEWELRY', prod='ID_CERCEI_Q1', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_JEWELRY', prod='ID_COLIER_Q1', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_JEWELRY', prod='ID_SILVER_RING', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_JEWELRY', prod='ID_CEAS_Q1', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_JEWELRY', prod='ID_BRATARA_Q2', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_JEWELRY', prod='ID_CERCEI_Q2', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_JEWELRY', prod='ID_COLIER_Q2', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_JEWELRY', prod='ID_GOLD_RING', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_JEWELRY', prod='ID_CEAS_Q2', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_JEWELRY', prod='ID_BRATARA_Q3', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_JEWELRY', prod='ID_CERCEI_Q3', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_JEWELRY', prod='ID_COLIER_Q3', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_JEWELRY', prod='ID_PLATINUM_RING', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_JEWELRY', prod='ID_CEAS_Q3', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_JEWELRY', prod='ID_BUILD_COM_JEWELRY', type='ID_TOOLS', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_JEWELRY', prod='ID_TOOLS_PROD_JEWELRY', type='ID_TOOLS', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CARS', prod='ID_ELECTRICITY', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CARS', prod='ID_OIL', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CARS', prod='ID_GAS', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CARS', prod='ID_IRON', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CARS', prod='ID_PLASTIC', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CARS', prod='ID_GLASS', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CARS', prod='ID_WOOD', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CARS', prod='ID_LEATHER', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CARS', prod='ID_BUILD_COM_CARS', type='ID_BUILDING', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CARS', prod='ID_TOOLS_PROD_CARS', type='ID_TOOLS', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CARS', prod='ID_CAR_Q1', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CARS', prod='ID_CAR_Q2', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CARS', prod='ID_CAR_Q3', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CONSTRUCTION', prod='ID_ELECTRICITY', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CONSTRUCTION', prod='ID_OIL', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CONSTRUCTION', prod='ID_WOOD', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CONSTRUCTION', prod='ID_IRON', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CONSTRUCTION', prod='ID_GLASS', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CONSTRUCTION', prod='ID_CEMENT', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CONSTRUCTION', prod='ID_BRICK', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CONSTRUCTION', prod='ID_PLASTIC', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CONSTRUCTION', prod='ID_HOUSE_Q1', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CONSTRUCTION', prod='ID_HOUSE_Q2', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CONSTRUCTION', prod='ID_HOUSE_Q3', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CONSTRUCTION', prod='ID_TOOLS_PROD_CONSTRUCTION', type='ID_TOOLS', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CONSTRUCTION', prod='ID_BUILD_COM_OIL', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CONSTRUCTION', prod='ID_BUILD_COM_ELECTRICITY', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CONSTRUCTION', prod='ID_BUILD_COM_GAS', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CONSTRUCTION', prod='ID_BUILD_COM_WOOD', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CONSTRUCTION', prod='ID_BUILD_COM_COTTON', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CONSTRUCTION', prod='ID_BUILD_COM_MATERIAL', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CONSTRUCTION', prod='ID_BUILD_COM_PAPER', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CONSTRUCTION', prod='ID_BUILD_COM_FARM', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CONSTRUCTION', prod='ID_BUILD_COM_CLOTHES', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CONSTRUCTION', prod='ID_BUILD_COM_DYNAMITE', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CONSTRUCTION', prod='ID_BUILD_COM_GUNPOWDER', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CONSTRUCTION', prod='ID_BUILD_COM_IRON_MINE', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CONSTRUCTION', prod='ID_BUILD_COM_PRECIOUS_METALS', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CONSTRUCTION', prod='ID_BUILD_COM_TUTUN', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CONSTRUCTION', prod='ID_BUILD_COM_CIGARS', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CONSTRUCTION', prod='ID_BUILD_COM_SUGARCANE', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CONSTRUCTION', prod='ID_BUILD_COM_ALCOHOOL', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CONSTRUCTION', prod='ID_BUILD_COM_SUGAR', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CONSTRUCTION', prod='ID_BUILD_COM_VEGS', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CONSTRUCTION', prod='ID_BUILD_COM_BAR', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CONSTRUCTION', prod='ID_BUILD_COM_WHEAT', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CONSTRUCTION', prod='ID_BUILD_COM_FLOUR', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CONSTRUCTION', prod='ID_BUILD_COM_BAKERY', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CONSTRUCTION', prod='ID_BUILD_COM_RESTAURANT', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CONSTRUCTION', prod='ID_BUILD_COM_JEWELRY', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CONSTRUCTION', prod='ID_BUILD_COM_SAND', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CONSTRUCTION', prod='ID_BUILD_COM_GLASS', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CONSTRUCTION', prod='ID_BUILD_COM_PLASTIC', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CONSTRUCTION', prod='ID_BUILD_COM_CLAY', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CONSTRUCTION', prod='ID_BUILD_COM_BRICKS', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CONSTRUCTION', prod='ID_BUILD_COM_CEMENT', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CONSTRUCTION', prod='ID_BUILD_COM_CARS', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CONSTRUCTION', prod='ID_BUILD_COM_CONSTRUCTION', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CONSTRUCTION', prod='ID_BUILD_COM_GRAPES', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CONSTRUCTION', prod='ID_BUILD_COM_BOTTLES', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CONSTRUCTION', prod='ID_BUILD_COM_WINE', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CONSTRUCTION', prod='ID_BUILD_COM_TRAVEL_TICKETS', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CONSTRUCTION', prod='ID_BUILD_COM_WEAPONS', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_CONSTRUCTION', prod='ID_BUILD_COM_AMMUNITION', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_TOOLS', prod='ID_TOOLS_PROD_OIL', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_TOOLS', prod='ID_TOOLS_PROD_ELECTRICITY', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_TOOLS', prod='ID_TOOLS_PROD_GAS', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_TOOLS', prod='ID_TOOLS_PROD_WOOD', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_TOOLS', prod='ID_TOOLS_PROD_COTTON', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_TOOLS', prod='ID_TOOLS_PROD_MATERIAL', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_TOOLS', prod='ID_TOOLS_PROD_PAPER', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_TOOLS', prod='ID_TOOLS_PROD_FARM', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_TOOLS', prod='ID_TOOLS_PROD_CLOTHES', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_TOOLS', prod='ID_TOOLS_PROD_DYNAMITE', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_TOOLS', prod='ID_TOOLS_PROD_GUNPOWDER', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_TOOLS', prod='ID_TOOLS_PROD_IRON', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_TOOLS', prod='ID_TOOLS_PROD_PRECIOUS_METALS', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_TOOLS', prod='ID_TOOLS_PROD_TUTUN', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_TOOLS', prod='ID_TOOLS_PROD_CIGARS', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_TOOLS', prod='ID_TOOLS_PROD_SUGARCANE', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_TOOLS', prod='ID_TOOLS_PROD_ALCOHOOL', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_TOOLS', prod='ID_TOOLS_PROD_SUGAR', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_TOOLS', prod='ID_TOOLS_PROD_VEGS', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_TOOLS', prod='ID_TOOLS_PROD_BAR', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_TOOLS', prod='ID_TOOLS_PROD_WHEAT', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_TOOLS', prod='ID_TOOLS_PROD_FLOUR', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_TOOLS', prod='ID_TOOLS_PROD_BAKERY', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_TOOLS', prod='ID_TOOLS_PROD_RESTAURANT', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_TOOLS', prod='ID_TOOLS_PROD_JEWELRY', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_TOOLS', prod='ID_TOOLS_PROD_SAND', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_TOOLS', prod='ID_TOOLS_PROD_GLASS', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_TOOLS', prod='ID_TOOLS_PROD_PLASTIC', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_TOOLS', prod='ID_TOOLS_PROD_CLAY', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_TOOLS', prod='ID_TOOLS_PROD_BRICKS', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_TOOLS', prod='ID_TOOLS_PROD_CEMENT', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_TOOLS', prod='ID_TOOLS_PROD_CARS', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_TOOLS', prod='ID_TOOLS_PROD_CONSTRUCTION', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_TOOLS', prod='ID_TOOLS_PROD_GRAPES', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_TOOLS', prod='ID_TOOLS_PROD_BOTTLES', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_TOOLS', prod='ID_TOOLS_PROD_WINE', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_TOOLS', prod='ID_TOOLS_PROD_AMMUNITION', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_TOOLS', prod='ID_TOOLS_PROD_WEAPONS', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_PRECIOUS_METALS', prod='ID_ELECTRICITY', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_PRECIOUS_METALS', prod='ID_OIL', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_PRECIOUS_METALS', prod='ID_GAS', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_PRECIOUS_METALS', prod='ID_SILVER', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_PRECIOUS_METALS', prod='ID_GOLD', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_PRECIOUS_METALS', prod='ID_PLATINUM', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_PRECIOUS_METALS', prod='ID_BUILD_COM_PRECIOUS_METALS', type='ID_BUILDING', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_PRECIOUS_METALS', prod='ID_TOOLS_PROD_PRECIOUS_METALS', type='ID_TOOLS', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_PRECIOUS_METALS', prod='ID_DYNAMITE', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_GIFT', prod='ID_ELECTRICITY', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_GIFT', prod='ID_GAS', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_GIFT', prod='ID_MATERIAL', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_GIFT', prod='ID_ALCOHOOL', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_GIFT', prod='ID_SUGAR', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_GIFT', prod='ID_EGG', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_GIFT', prod='ID_FLOUR', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_GIFT', prod='ID_MILK', type='ID_RAW', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_GIFT', prod='ID_GIFT', type='ID_FINITE', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_GIFT', prod='ID_TOOLS_PROD_GIFTS', type='ID_TOOLS', buy_split='ID_NO' ");
        UTILS.DB.executeUpdate("INSERT INTO com_prods SET com_type='ID_COM_GIFT', prod='ID_BUILD_COM_GIFTS', type='ID_BUILDING', buy_split='ID_NO' ");

    }
}
