package chainrepublik.kernel.net_stat.tables;

import chainrepublik.kernel.UTILS;
import chainrepublik.kernel.net_stat.CTable;

public class CCountries extends CTable
{
   public CCountries()
   {
       super("countries");
   }
   
   public void create() throws Exception
   {
        if (!this.tableExist("countries"))
        {
            // Status
            System.out.print("Creating table countries...");
            
            // Create
            UTILS.DB.executeUpdate("CREATE TABLE countries (ID BIGINT(20) AUTO_INCREMENT PRIMARY KEY, "
                                                         + "adr VARCHAR(250) NOT NULL DEFAULT '', "
                                                         + "code VARCHAR(5) NOT NULL DEFAULT '', "
                                                         + "country VARCHAR(50) NOT NULL DEFAULT '', "
                                                         + "x BIGINT(20) NOT NULL DEFAULT 0, "
                                                         + "y BIGINT(20) NOT NULL DEFAULT 0, "
                                                         + "occupied VARCHAR(5) NOT NULL DEFAULT '', "
                                                         + "area BIGINT(20) NOT NULL DEFAULT 0)");
           
           // Indexes
           UTILS.DB.executeUpdate("CREATE UNIQUE INDEX countries_code ON countries(code)");
           UTILS.DB.executeUpdate("CREATE INDEX countries_occupied ON countries(occupied)");
           
           // Populate
           if (!this.reorg)
              this.populate();
           
           // Confirm
           System.out.println("Done.");
        }
   }   
   
   public void reorganize(long block, String chk_hash) throws Exception
    {
       // Load checkpoint
       loadCheckpoint(chk_hash);
    }
   
   public void populate() throws Exception
   {
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEwY2LDnb/4Xfa2CG7dhIp+9oq5m9/ADvELW9IUgbQNp/F6zM2etAZf1JceuLstlxSoZLZ2nOX3E4ohjZmvbiqzw==', country='AFGHANISTAN', code='AF', x='2280', y='551', area='652000', occupied='AF' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEn9t/OjiQ275OiaVX6ASfq/lTL0vH+mceuPT6Fd6A3JDwAEyzuGh0eh1ef0+EhV2I+qn0//A85NtziHSCUeYnVQ==', country='ALBANIA', code='AL', x='1840', y='480', area='28000', occupied='AL' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEh223/yLaVDwt0KHRbETRW7tQQx4nqtg4+8bpYxpgyu1462jpxEiXmWQ9tqufGx8V9s8JVhrrkaseiX7L9hocTg==', country='ALGERIA', code='DZ', x='1670', y='600', area='2381000', occupied='DZ' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAERITd7+5w+6skIj3crdrBOAHWykoM1Vn3vyf1+CIfETuWHysNJW5kgGGA7aVPlo7JYSyIwILD6MS+ApRZBrRJYQ==', country='ANDORRA', code='AD', x='1670', y='463', area='468', occupied='AD' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAErivtW005L4I/TMGRBa+fJfU86GODyF4Vdj14z9YRucbDx1hysIMeb/W6EowFA/KomGNwrbRUJ9ATnBJNrDglag==', country='ANGOLA', code='AO', x='1816', y='993', area='1246000', occupied='AO' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE3GK9/oHlRm1XxqbWB7xIXsQdvuFuTT6HnKhLgGhMiEJZxWPw8JhYiVKkAqdNg0Fgrz4XGk6mFktjoo1ew778Cw==', country='ANTIGUA AND BARBUDA', code='AG', x='1061', y='733', area='442', occupied='AG' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEPqELrzOT614kOvOaQTDl/vBkoyKqaGMRoH4oyd3Zjlb94aTr2Qp2SB7CPg8dCcgXF78QZ6xaN/Ea9HGn+lPmkw==', country='ARGENTINA', code='AR', x='1018', y='1217', area='2780000', occupied='AR' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAET3hLzm56073U++ygcC46vSkN1qzTAqzwsY51nDuvTnrw4mzvEkr4paQW//sTeAaxxhmYY3UxoPW0EWu+ll5DUA==', country='ARMENIA', code='AM', x='2082', y='484', area='30000', occupied='AM' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAERMoCKcvcwyYdzDNHT48xaO5EuFVZSlp+ECulyzF5faARwC0VO/6BVGPKMHJl5nYThNj6l1Q858vNuvoU08LY0w==', country='AUSTRALIA', code='AU', x='3000', y='1111', area='7600000', occupied='AU' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEnAMIzfvHU8P06Y6VJdlCb7hrWtoPuvsxT+93B6wD4T9ZAuN1XDOuuEQmIyQ8j72kEB7uJO4PY0yxhPaNcaDjTA==', country='AUSTRIA', code='AT', x='1790', y='413', area='83000', occupied='AT' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE1cGoQ8CEb5zT57830erLZ/66dP60dzvIA+eYPekM2UvEvVbzPWI65jOzS/u6JaLmzUEtbBSdHJiI4RQx5YOruw==', country='AZERBAIJAN', code='AZ', x='345', y='1', area='0', occupied='AZ' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEm05SMZ/YtTC+3W+3Nchhdn6FQ8QE6IVbN0VcWIU2uT+BGc5qRsDGHdwt+YmxnzJnq7FvwVcUCXr7IDYn0spjGQ==', country='BAHAMAS', code='BS', x='22051', y='1', area='0', occupied='BS' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEVVdmSjVIDh0cn+7UGpQe8xRAkKqCKRUOrAh0siv7/AkS0bgXMPggqHuRZOFgSE4TN0PE7OBQHHV1kS9xQho5oA==', country='BAHRAIN', code='BH', x='643', y='1', area='0', occupied='BH' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEIHQhOQmdi2G0eKRXb2NENluuWOC+SifMMIFr82Wzsb77wE5Kfku5JGYOAZ4YobmkMOIhBQwMWZpMcJziAk5qdg==', country='BANGLADESH', code='BD', x='154', y='1', area='0', occupied='BD' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE9c6TKjyKemN5Gpk5qR0RmOhbmxlyAAdpvVuRPKLM2rheLvotamTOfnSs6+g0suIKC9fkAiIjsv/YHZs2WvLnSA==', country='BARBADOS', code='BB', x='8971', y='1', area='0', occupied='BB' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE7V6aSglivqzzER2OyDbsB2JHjjjuIAHVWcaX0fc3tLO4EN3RiyxhH3jWv9BkHdhqbjhofaSXxTBsrggCC8rXIQ==', country='BELARUS', code='BY', x='1923', y='358', area='207000', occupied='BY' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEC9/+bkVVa4oOETWOnF4IwK0AYPvpanbqONJylxDlJd0SVyTSWpGlmEZp+ZgH4k4riWJOdMUwPfyy9fz5aTXL0Q==', country='BELGIUM', code='BE', x='1700', y='385', area='30528', occupied='BE' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEJP5BU4IL3uyDgScY47drlQE5fnyChZHP4WbxaLLA2oIiCikhWL013B3u0d4HIFj+FjyxETUM0+66phzJAVAHJw==', country='BELIZE', code='BZ', x='10395', y='1', area='0', occupied='BZ' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEhRLEweokVpSJpwS8o2VkvuSfpHQvquWYdJq2g8+ZEf/kwWw8Fcj1U5w8ozEK0IeVfu7d40dMqMm4E5Wao25lsQ==', country='BENIN', code='BJ', x='0', y='1', area='0', occupied='BJ' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAECJIYDVtWH+mBJFNSI+xToERQYU7R1m1w9hitvsc76V4aFYT6gEy9zz85Ud+dqhzcmsCHE5mMeolkSj+ZiP0jSA==', country='BERMUDA', code='BM', x='0', y='1', area='0', occupied='BM' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE/kQn6JpypiRe2r1LJv7Vrd4jUCJnU6i9uATkI0N45BG9Bkdc62jwn6/xv9yhEAxLDPdyJUROmrlyzIdPk1U2UA==', country='BHUTAN', code='BT', x='2464', y='1', area='0', occupied='BT' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEQezs7x1mjyoz/j3ptVjbyuHslm7p5WUM9HnLWdmBMIeIDzns06pS8E9k4S87Na8/JqZcLVbokpj057Sv5/0Mow==', country='BOLIVIA', code='BO', x='700', y='1', area='0', occupied='BO' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE9IlC7FgeYS4SaovwCpapxiPA9bcYMpk1EtIIO6DVaw3Rr1crop90lwhgoUUCDL4aJUaABSVdZ6F5sgEr5OKZJw==', country='BOSNIA AND HERZEGOWINA', code='BA', x='1824', y='449', area='51000', occupied='BA' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEW5BwK2Zb08Mjt4XNwnw2Z+EfRypWr+5RYMEB9DK68YBynNxnE11vw9NRXgJTDOgOnOQ/nu/Mrj/8O+CN4Epefg==', country='BOTSWANA', code='BW', x='2412', y='1', area='0', occupied='BW' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEIUQoayht15eBxfowbZMws162rXPNwF+Uu/k4e8AWAmJQMAYRfzwJF13Mt6rLMKW04nmN2kwNIThrfwXuUICwsg==', country='BOUVET ISLAND', code='BV', x='0', y='1', area='0', occupied='BV' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEmg0G6DJIpenL79hJiDkto8IzUVuZ9DjWepgVEMEHxPc8VOrUG9imKrn3Y71sSZNRkYh1sFIa6I1eE1HqtK5O+Q==', country='BRAZIL', code='BR', x='7456', y='1', area='0', occupied='BR' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEJqQ33V8KNfuCyLZR23S9qpbfFNe7KDAEUfwtkR02XLiKZMXZHTTEmrqwiwS+xefZDBaK9g0XBtzjkm5pz0C4OA==', country='BRITISH INDIAN OCEAN TERRITORY', code='IO', x='0', y='1', area='0', occupied='IO' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEFXAz4t+koLLoHO8Pl7AIoJu+AALUOPsi4Gd3Yg3GpjzRhC1eFUT/cakroy1UspQZapiNV0/EbnEcSnX22YVXwA==', country='BRUNEI DARUSSALAM', code='BN', x='40', y='1', area='0', occupied='BN' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEpcQqDa3ebGcut2aBROEY9XYhWCCIM/NNG0/wxqjLx9gf/jedFA5lQgpLfAofNnd9oc4ruQ0gG8dTE3AzqOtl2Q==', country='BULGARIA', code='BG', x='1890', y='464', area='110000', occupied='BG' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEE2PA415sG2lmUdS+lMxWoBj8CK4VTYhyUnvK/ouEnJjXZmgRGDHrYH7Z+n5aKR0tOH8GeCF1dxOlLWHNM7kpTA==', country='BURKINA FASO', code='BF', x='0', y='1', area='0', occupied='BF' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE3AC+PLtj+f1dE4QOrJzXWpGe3yNlcRfpOizWooxXyQStLYbxZzLa5iYSigrqAY+nTfJFs6oKf3lQIypqbH4B8g==', country='BURUNDI', code='BI', x='508', y='1', area='0', occupied='BI' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEBVMFdFalN4Uyvuy9pKkDY4FZxlSOrtZ1tA36ka5OpVyuXUjqYETgc9bwwNSxTKWj8gXxNJsE3h02ZSUWl+JFvA==', country='CAMBODIA', code='KH', x='0', y='1', area='0', occupied='KH' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAERuJaOZu+FJC09M4tmceUQ1fUUBikWr6lDjbQqOhMBCs5JlgDb1r5IO0Sim6EcFBKgVZ3ApNmP2s6VH1rPaWGeQ==', country='CAMEROON', code='CM', x='44', y='1', area='0', occupied='CM' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEFL+MOSl/UHok39CBtE/azKHdHBM2jUOAe7zrIRSIDA6N3yFGOyA5pNxX5TEmZzyXj5/de30/Gy8vzBDeuJl+5g==', country='CANADA', code='CA', x='995', y='1', area='0', occupied='CA' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEDv9iG0KLjDCPYkWAM8B8Zkl0UWa0W9xAFr8/bZSZm/uxQa4+DfkG+gb+PaLg0FJZppNzXCdPuvb9asMGR62zzA==', country='CAPE VERDE', code='CV', x='0', y='1', area='0', occupied='CV' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEXDi8kh9AnuUaj0NLHnu5xPjUXvhTTJ+2fXyR1IuXOdLhBrFtiPxRJewFezb/KrPu6VH0swLZEGAKoiOLawcomw==', country='CAYMAN ISLANDS', code='KY', x='0', y='1', area='0', occupied='KY' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEtojNw6bkwB2luTzHs64dQBFuqRgKMTMDN1+EJAZZso84UYskqA0MsfZgiNnt6RwVtvujQOszbCRccXfYWm7bJQ==', country='CENTRAL AFRICAN REPUBLIC', code='CF', x='0', y='1', area='0', occupied='CF' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAExsOrFIa8ML8o0NpRl+laiSX9kSlQByb1uJYRnpKteFNL98gM8nJPVey0HSCxNRnmHX3Usxl22wI9es+e1yyhDw==', country='CHAD', code='TD', x='5065', y='1', area='0', occupied='TD' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEHTZp3BskBYX6A0Tu51giPyOBrx+YtWUQ83CtHbTyu4L66FfIoipUNvyAIQTLY7Z3oTpKfPb2Gm0ZHTF/km5PWQ==', country='CHILE', code='CL', x='658', y='1', area='0', occupied='CL' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEbzBxrz6SwAWmYf8XB5Q/Ikk78FkvbBhKT6zODbCxHHSqEa0qZxaYZqaP6jHa/3TY2nQJ7Kz6n3GKqgj8PBw8Mg==', country='CHINA', code='CN', x='654', y='1', area='0', occupied='CN' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEOi5/njS2W+dmJkA4yNywnvt5JrV0FlVok0vQLBitzQt72jKsCfjlzKQkbrHcmoLPZ9x0yAnzCMA0c0Tz1dafGA==', country='CHRISTMAS ISLAND', code='CX', x='0', y='1', area='0', occupied='CX' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEm9jW+LmpHq3qbAoFuilsBmsDaAjMO982SB4k0WdqHo9ekLC5Do4edz5jg+TsPPSlFxdVEW9jo3H2wXFLTuB4PA==', country='COCOS ISLANDS', code='CC', x='0', y='1', area='0', occupied='CC' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE85YfXA4p1mFO9jtxIVuizz9wH5R/CNW8hZ1qWkgpZhrb/EDxi+BG904PKhh2c/OwiXnePl9/Yw2GF349ZlFQaQ==', country='COLOMBIA', code='CO', x='1489', y='1', area='0', occupied='CO' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAElfWNxy2EHbPUZoaQBO18bB0H6UjuiDWP17aUKSwKyHDi0QVke1Wj+RS3gMOBE+ecgQRBN7BSfsRz4bB8KXc4xg==', country='COMOROS', code='KM', x='0', y='1', area='0', occupied='KM' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEt8qVCS5/eMzQkOiPHhW2vFs+Y1QCFxS1PC7mcde+I+t7MJi8EyQ7LxhI8f6nHV770rUOMhOOtSFT+ifaMLNIhQ==', country='ZAIR', code='CD', x='0', y='1', area='0', occupied='CD' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAETQaDIMtMRJ6twShuZGodVo4Fg+TCOLt58Q72PAcoSY6UyfCi4hgw2dXotI4nmGfExwhxExXOgQ9lhXGwNXkN0g==', country='CONGO', code='CG', x='0', y='1', area='0', occupied='CG' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEGKbbsY8PkU2tlddzL6orgYCITf4dB9Th5FBoEtSyKICnS/IIaYH4oOWmd4hj89EmjAYDE8OWAI9Cue3dUoSnfg==', country='COOK ISLANDS', code='CK', x='0', y='1', area='0', occupied='CK' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEaHwGZnRwIfwqo2n+EJQahuxgTd9WHE4Ql25RggtPs65Wx/ObOzUCVM8yUjxDtM0j8ZKBFPhoNrkCt3lvJ0bszA==', country='COSTA RICA', code='CR', x='202', y='1', area='0', occupied='CR' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAECrasrUDEDpzd90yMxyc8oy1V3DHP3FLpycdvILJMwq17jM6aAqFm5wFX63OFZeLA+D1Kn1+ArRIuwbZg2haTAw==', country='COTE DIVOIRE', code='CI', x='0', y='1', area='0', occupied='CI' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE6r/GR3UvKBtYAm1LWrDgLFLXLII0A9K4myO51TivncuDBls72L7+ub5K6/Pa3GB3m2UrIBqmWbkGgDO+PfFCPg==', country='CROATIA', code='HR', x='1808', y='431', area='56000', occupied='HR' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEzbGXOMK8QbvY722585BFib7zPQE6uIYoSyM1Yq6jre3ki90u22YXTlLfux8rJxBcH/PdTkaNzFIAhUTOlP3MEA==', country='CUBA', code='CU', x='4715', y='1', area='0', occupied='CU' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEOCRy/1Uyf2wFBDxRg1yRmL1x6cS+A1aoOwbOBd8BiOLD4wKUP0SaxAG80fo+Yq+DlqpPQLKFVDP43Y09Sx4SCw==', country='CYPRUS', code='CY', x='1972', y='537', area='9251', occupied='CY' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEDj9plXgtPp3kwQ7v6VZE5p9S9Fd3oC31HERsiZadejt/+2chKKGDsUHw+w1ADM7li50x8wGffOwcVOd9X2fklA==', country='CZECH REPUBLIC', code='CZ', x='1790', y='390', area='78000', occupied='CZ' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEqQzX2k4OFMvCSvHG7qE38qEeWjp0bvGpwvd7/x4y5iv14EHguXGLCmL2j7G1txh3oMZWczyItcEE/dqMUtSMvQ==', country='DENMARK', code='DK', x='463', y='1', area='0', occupied='DK' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEeeGlOkZaIqREGvHHM1ekKMh5oDqp43B5cIhjr/ZnV4LjaopuLPpFuR8DsuD0WWt7Krg5fc9NKQBGd3I8I8DH0w==', country='DJIBOUTI', code='DJ', x='0', y='1', area='0', occupied='DJ' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEyKl2tKhzMbSanaGeaNA55JEm04jxdWpxTUQbAR/mCBXqKcx1AvjVJWCGRqZKzUyEqnqz6UO+URsgv22XhO6bUA==', country='DOMINICA', code='DM', x='11', y='1', area='0', occupied='DM' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEblxaVhVXi8EXp4iNqKdKtmWec4gikWaF0WSW2NXlRTqCi7IGUS0ZCYj0znecv+j3vQSazpf9zQuepDpadRfSYA==', country='DOMINICAN REPUBLIC', code='DO', x='607', y='1', area='0', occupied='DO' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEJmSGzdwFg2eqb/mNssA6yzVULeurcyd5PNHFPMOTCeTRaBUytXsA73ZiLd+Lonsz8V4+GI7/3z7qQxqck/qp/Q==', country='ECUADOR', code='EC', x='1578', y='1', area='0', occupied='EC' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEG5GqI5x4XznGf+ELNe8bEYWdATLQ/ZdQ5//yr/A43CfAGo1eyA/6v1k8UQbzOoWD+9AqCIEFgA9byZxgww3Ukw==', country='EGYPT', code='EG', x='289', y='1', area='0', occupied='EG' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEDsELy+RpDQTsaHRtGRtudIQU+gDVK6EMFQuyFCp9bh6UxYxo2hq9kxIjSBc2i/48IwYv/TmF0RjILvbk9Ux6Tw==', country='EL SALVADOR', code='SV', x='2131', y='1', area='0', occupied='SV' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEUbOMb4jg2viYmjoRWVyDhnN1Qkgh2kNqlLt8IabBg/lzFcFV2saTZdfQxQxVk2tm4Mqv1WZmM4bjwWHcss3b+A==', country='EQUATORIAL GUINEA', code='GQ', x='0', y='1', area='0', occupied='GQ' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEEHZRxYLks5V2A5BCRyWn15qTTvX3Cw2SWiwEjGIRbRbBUsygbGeE0MBjHT3XYBTWvukOS/cP4OhelDuFLYaH7w==', country='ERITREA', code='ER', x='0', y='1', area='0', occupied='ER' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEy8xaAPhCqrlq3pLzDe6l7zYsG7KVZD+rinmUv4Vez/PvfwaATGCo4gpB8NyzqkFPv4Y/Ikt8R9kAfooV77o8WQ==', country='ESTONIA', code='EE', x='1890', y='300', area='0', occupied='EE' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEWqpu5imisG3+pkrOjH2OPp1Ty/WuCxqOq1DZdbqDo4VzTAgu70M01whGCV14OFNQykLnk2/+D1xD74cgDnZp2g==', country='ETHIOPIA', code='ET', x='0', y='1', area='0', occupied='ET' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEGbUIq4PHOY+Amp8tZtalNHf+53Yqm5DrU34yRTIgcduplXr6et44JjQuHhRKIP3qLe5Oxo05ceYhFYs63hN23Q==', country='FALKLAND ISLANDS', code='FK', x='0', y='1', area='0', occupied='FK' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEayY/vHAEAM61/E4p6ulrC59TIZHBOUfzcZUxDONbptsZfgua//z43bHbrEVy2PMA8EfTKQQ3InBdWLXDinmjtg==', country='FAROE ISLANDS', code='FO', x='0', y='1', area='0', occupied='FO' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE0VXe2UKT9wYEt1a76dJvf3gu98edv5anYafsxeMHU5HydsiJ1r9SJxQnlp3akxi2HvabXc6QKAZOl+hEFWs/WQ==', country='FIJI', code='FJ', x='1368', y='1', area='0', occupied='FJ' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEi2wgx9d/kzd7hppaF15T4Xbo/JpP1wFDk328zahe6uYWgEqd0QwfMGQiIu/RyyhuXxd3C+JUCJQ3ZjSZn0YoOA==', country='FINLAND', code='FI', x='1900', y='255', area='338000', occupied='FI' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEF1MIk315tUfoXhUkuJO8q3AyOwnWrgqHu9mu5RemMJM145ALlFMKP2WA99Y8OfV/5MgdgtPMXej5LahTQnM1Sw==', country='FRANCE', code='FR', x='1670', y='427', area='640679', occupied='FR' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAENrad8boyB8BKCAydycXXWQiGAQMbSMwAPpxVs5yTwjre/1dQKviLIHBLO0997uC/LHL8uPsKn3chtoR2VlAJhA==', country='FRENCH GUIANA', code='GF', x='0', y='1', area='0', occupied='GF' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEYUI08IMcVE/x9988PC+X6QKXJibzFMjl4NxUxyNRV9h9WzTU9WxDXJ1SlBJTscVzO87fjKoXJk+x01OG95Qjhg==', country='FRENCH POLYNESIA', code='PF', x='65', y='1', area='0', occupied='PF' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEvS6wb+SPUlLo+ovL8f8Q0PvPsAjnR/kBtBEA3ssAAkNmwwzMONOZ0w9c+3XN5Sbt+Um/TP7Phq6el0fRbo2e6w==', country='FRENCH SOUTHERN TERRITORIES', code='TF', x='0', y='1', area='0', occupied='TF' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEDpK0GlYcsE6yD7IIRyYVFx+d7qrIKRf8Bf748u6nnT+fOfnvKUyqfQPM//WpslBAB59rBlcrHFShlx/ThGRxTg==', country='GABON', code='GA', x='0', y='1', area='0', occupied='GA' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEEAuMeguGWDvHz0QTpLj/MxZjRwoDigltZqhlFG09mlBDcu9txpPXoSw2yZmsQdlfa/oPKagdVs/aN21EJypErA==', country='GAMBIA', code='GM', x='0', y='1', area='0', occupied='GM' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAElbubzMjASBJIQi8BRfXASCtJelYjw6HEJNn7Pj2SwtYSovbbXWHXBOTmirEx8pn8E0lAMT6CYoeoaHrmN8e4kg==', country='GEORGIA', code='GE', x='90', y='1', area='0', occupied='GE' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEiU+FgDrRQhfRUMJHaJ4XiMhuKqH5hyekee17wkMh/oML1GcimUj+bd+cL4eh/s2Y1Ng97jzt4fiYdS3qNrNzEw==', country='GERMANY', code='DE', x='1740', y='384', area='357114', occupied='DE' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEo78DWhSv0bMQCmJW21ltqumdS/HzbXXNsqvQuWBuIn6Sr47bc7UlslqGcYYMDfg8erkrLWLc1jDawai+JmH6+Q==', country='GHANA', code='GH', x='109', y='1', area='0', occupied='GH' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEDwbc+2miqMJ72weeHL5WigQe/cBMTV0ukTS+s7mfh5hjLK9DAWy5I975ryVhQxedhiL1arUAO/NWxEN0lj+lDQ==', country='GIBRALTAR', code='GI', x='172', y='1', area='0', occupied='GI' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEx6GelT4j13I56Of1ZNfwH5WmvEVXCsAZy5wctILTncgCFXXhL3TgpijA7igqO7TpN/Y+KdhTFBiWoBzrqS9GEQ==', country='GREECE', code='GR', x='1860', y='493', area='131000', occupied='GR' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEzU36dPreC01jdJHl53Fk4caQb50Or6W3GMYDtZAPQPwSuEUP8AwaxHAWMrkMiMTOyvVCOUGTgihQpofSw5wKPw==', country='GREENLAND', code='GL', x='19256', y='1', area='0', occupied='GL' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAERuHR3Lzm8Zq/PrvcMutDfDTSrD1sxPigrFJl1eRpfvEm+UBCxSouL6NvANwBtkc+lOb2gnapNnDisdDHX+7Ljg==', country='GRENADA', code='GD', x='14', y='1', area='0', occupied='GD' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEN2skIqBma4zQAR/8aha9i+gWNHVM4VUqo9e9Mu9XFgDG4OOIkAzhjZhCE4xwpkkqyFqe1T6DtooLFTp3OaL8gA==', country='GUADELOUPE', code='GP', x='0', y='1', area='0', occupied='GP' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEg+cFgHWd8/7J8ThmGUGLecm2716TQg19InD7/yy7ofxT9l1uFhV+MLgh6I1jfWkHyA4tnadaJBDAVeF6dbQuWg==', country='GUAM', code='GU', x='0', y='1', area='0', occupied='GU' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEWH+b7tdvY0e/Oomcfg+Xy8atRus18vjOe9U87ZwV9vmtbTJKIq+w8mLi4Pej0PDk+/hfww0OcLW2PbcmYuevKw==', country='GUATEMALA', code='GT', x='11', y='1', area='0', occupied='GT' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEqGMNf1PBeIHix0BTy817PPHIgtSP9Pdwv4a5J9+E3uOEhgMtPxKUuLbn4hXQm2YxPzC+KK6Ch3KpNPBcM7DRpA==', country='GUINEA', code='GN', x='0', y='1', area='0', occupied='GN' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEM3kLqd34aBdavHcXYmveSehZL91RjAClA8s+njErjZGlTk7SgoY+p+pvGyfRcO6coet92+ZvmwRCgRHxV5n9ZQ==', country='GUINEA-BISSAU', code='GW', x='0', y='1', area='0', occupied='GW' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEMvphM5aynElM1DBJTv/rYA2CpJvI772Ur9Jk8bay6WKcNXo92KnYx50z+b3IwwNGiCbS00DnFB+dFbuha9tq8A==', country='GUYANA', code='GY', x='0', y='1', area='0', occupied='GY' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAECS0mTp9nX5T8v71ot0m4KMUUw7MLjoNJAnP4dTThQZ/4D00xezcbUT0V9yeUvex198jKC0nF7XbXS65OTb5iRw==', country='HAITI', code='HT', x='842', y='1', area='0', occupied='HT' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEf5gLpA1EYgCil3kTG0ghxNEl52ckDcnRhIIJaAijYF0FBoWfEQeM8KDpWPteBOLoD71WQUqzwOAUz2McPDH+ig==', country='HEARD AND MC DONALD ISLANDS', code='HM', x='0', y='1', area='0', occupied='HM' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE+3xpXrL0HPrCgg2e4uzF64JQ2Bs+zmSb0Djy2KCzlvwmWklJfHl4LyIhkf0f1LA/nTFBrJNlT4ij6Z4772P4Hw==', country='HONDURAS', code='HN', x='13', y='1', area='0', occupied='HN' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEdu0C8M3JyRKvKm6sDkZnFRkUw62iEKpdV28DiSXT81D32NSjVO0haHKduJo+qQ3B4DPqbPiInDauGUcpXYLsoA==', country='HONG KONG', code='HK', x='124', y='1', area='0', occupied='HK' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEvyrAUs8hYqixoJECeAcZbgc6k7TFCkfiyZG8RELMoHHeG9tHkbeDq1dIOnnxeTXj3vvaP/xZmjvuQmKjwsr7MA==', country='HUNGARY', code='HU', x='1838', y='420', area='93000', occupied='HU' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEhYoAdFStQg8S/zun/lUPbzU4pLUjgbshWJl2zyEBjG4o9/o7utQNAR9mHdc4Gu8VOsPg8XnX3kORxVh6QRtVCg==', country='ICELAND', code='IS', x='0', y='1', area='0', occupied='IS' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEOSyOFcnpGNuLNA4WPzXiBF+H6QODImpwb0hexVg3LN7+wZ6DArLKjeFLA7PExhkHeB2hDzyaJy7CMqD9DEEYow==', country='INDIA', code='IN', x='1834', y='1', area='0', occupied='IN' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE8MoNbsRi+O/CgHYK0XW9L2t+9p3hNEkED5YFa7iIBUVwildfQMGdDc8gLASfjkgOVzwM+XI3/hiJabsZM4ESLw==', country='INDONESIA', code='ID', x='25302', y='1', area='0', occupied='ID' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEHQS/m2L1iiIlCweygUZNP81/KKjH30XCcVjqM1xYUbnp6eF59+iOfvjMUhTsyjL1lKkMQj+vfpPVnej82r4taA==', country='IRAN', code='IR', x='561', y='1', area='0', occupied='IR' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE8vR4yRcCOpiV4K+cUlO9d2dWcpXrO+77VbESGkVwhrgmK4gVzuHMOXjwgpIXyOqF+U8I1R6hJdIvQhQZ9yOLyw==', country='IRAQ', code='IQ', x='11', y='1', area='0', occupied='IQ' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEKIq65IBqO8LzLZfpD7n6k9H6ES0OOGOjmbLcOCLNvUMTkLcb6VzXTlC/BwbdYnZvI3TUH0ks5GrRDbNieL4C7w==', country='IRELAND', code='IE', x='335', y='1', area='0', occupied='IE' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE+gx/zit/IGJyw31NGErZ7pUFyUBlE5LAsLdoJ12wtnu7/c+1CxUyJNth4N5WgnEXZgVM7GnoAdXT96KBE+Au6w==', country='ISRAEL', code='IL', x='303', y='1', area='0', occupied='IL' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEhKhg9k1IgWGDxed6kK456riDaCMXlGI5u1lLDmo6MJB6FEec1L8QDCxk6AulUhHbXM3JGv5HhbbBa9oWVIcDcg==', country='ITALY', code='IT', x='1754', y='441', area='301000', occupied='IT' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAENcyITRu3UxSnuZJYtHLH21J9iFdiJFU/hKv3IGthkxdb4mf8ilU0Qv/3TWotZuF0jAIdlDTywgU+7f5qH3hvsw==', country='JAMAICA', code='JM', x='9833', y='1', area='0', occupied='JM' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE8JpSesBPojuvAw1xHbge3E4olDBvZtIyHA4m9B3SEuGmzM1Mm82H5R4oUq6pA5qQZ8I1NVN/WTGc0Cq4RPh1KQ==', country='JAPAN', code='JP', x='494', y='1', area='0', occupied='JP' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEka99njSp8Mt458+RVFcVDpew1apAvP+y5I1cr4f5AyKMJal6p/CB5ZjNmWsKmnfcmY4Od0ncfXW5oJBv0EJUIA==', country='JORDAN', code='JO', x='0', y='1', area='0', occupied='JO' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEcUlrQxRj6xJv/ltmwN+/ct9vqWKmCeOIDDrQ8tL+qjBa+XOkUQKR40LXdMj3bDRQT2Zhn0Hg7IMvQ7lv2AwAxw==', country='KAZAKHSTAN', code='KZ', x='103', y='1', area='0', occupied='KZ' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEtTaaocK45tWGKBtRv+lVwN2cZoFf+OxMCECDp4/omzHiEVGClyzl8rvLFnCPe/zyTR1QuI1gdx/eolCtzmCUAg==', country='KENYA', code='KE', x='826', y='1', area='0', occupied='KE' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEvr6Re5VIJCtnFmIxL9P9KUVx5TFkME2q29sIsoTzMahOiRDrd55/QHvWoc0J6OSWMbXTgky2IgLw8Kw4WakzNA==', country='KIRIBATI', code='KI', x='821', y='1', area='0', occupied='KI' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE7h/HVl+4GwPVaXcE7Oj7xVF+gccqbs2PH4kyF79OgyDUg1bbaYf5yn1tNjAmAFIQW/qyMJLu6qgtFYudpeQScA==', country='SOUTH KOREA', code='KR', x='336', y='1', area='0', occupied='KR' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEp5DxPBVc4vvxmCbN2pZ/Bs07qrhpbzVrBMSZ+NV+wK37btTVE2r7jJ3yWz79pVzc90W2E7j6OvC1mhTsepgvjw==', country='KUWAIT', code='KW', x='98', y='1', area='0', occupied='KW' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEghBS2SIPlRJTMw4JpCsREW4cYr5DL+xHtodev/950il7vlRErHUohrtnwZz+Q7uM36MwdSAyYAOmiudzgvuvWA==', country='KYRGYZSTAN', code='KG', x='0', y='1', area='0', occupied='KG' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE8PDazc1K8nkt/aJTNmd/aSSWsUvcpOt60DKSl4vQxnHnHFZCC21ByjUGlrhDDxsmLKry7ueBsZLTKGq2ICiA4w==', country='LAOS', code='LA', x='1011', y='1', area='0', occupied='LA' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEVCYNE8YKjnw88Q0T4WCoPeWDtC50AbfThLfOYyWYdUI+RssxeAQUnArQumm0kVaY/mgVYR44ADcOsZWf7mhO9Q==', country='LATVIA', code='LV', x='1896', y='323', area='64000', occupied='LV' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEs1Tw0wdjFzUHAmZ0xBIDRenWLzLD+2PdcJR9tzax/LRbHdDD/7IUxeynwYaKLEndO83MYn6WPeCBqXJCkBN4LQ==', country='LEBANON', code='LB', x='0', y='1', area='0', occupied='LB' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEUSb3mijUDMj1KPSiM29b7VR+f4ncyNyPNwHv95L6ye4EsVVmTdVOuESfcfTpfw5XK3zciwQ5W8OnKAQlN6h+7w==', country='LESOTHO', code='LS', x='0', y='1', area='0', occupied='LS' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE9SZXTpu4fqyKio+U0lm1Rxo9ww2f1fry4u01D/2Eldqc7u5z2abjgGk3Y+OUkyVKVHfGTjbUwBZo2Z29UjD4Ww==', country='LIBERIA', code='LR', x='0', y='1', area='0', occupied='LR' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE0tpqEk7ZC5QKtbokfX/iX8T52ywolI8zfRzEXGySdBu9uarGLBi0Wy7sRogS4xE4So8LTf76MzO2uFn+8WaFVA==', country='LIBYA', code='LY', x='0', y='1', area='0', occupied='LY' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEwJAG24fjJ1qjlA7kgbzJopmFDxg6Pn6oRBABX0qPm2POLbLcb9+gNuF0dCkesdgzti4oRlkgS6N/pEjhJSghvw==', country='LIECHTENSTEIN', code='LI', x='0', y='1', area='0', occupied='LI' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEXWB3BCkppeMZOJCl5VkX3of1yGcqK4c48FzX5pVMYVdXvVoUia3WMC2rgvWbYQNuxKZOrJRKBYkmW+KbySus4A==', country='LITHUANIA', code='LT', x='1882', y='344', area='65000', occupied='LT' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAETclT1O3kS6y2fIDcUwY0YyHQWkrPaHEArUIiQFdVgR/EBcWVrxOuhHILyiTXw5Q7fkNO74BnW5oI8vonzHCXVA==', country='LUXEMBOURG', code='LU', x='1700', y='390', area='2586', occupied='LU' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE8MgXqtajstK7cb4aQ1PCh5hh5PlEfsEwphx1upWvg+VM8Qgp6mvU5T/swSyej5HjC9mnMZyrG5xUhG4fOTUULA==', country='MACAU', code='MO', x='6341', y='1', area='0', occupied='MO' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE8KpMS9kbi7/YQzkRnnR5+87CyYvhbDlWdB3Av5nK/GcEN6m7kFkId0NJWEEaFWmoZUJatzfMIVRlEN2J8w35HQ==', country='REPUBLIC OF MACEDONIA', code='MK', x='1793', y='427', area='25000', occupied='MK' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEmlew3xWXbIeB96NPwEfZSGPHUkF7Z25O4oX2C1Em2g8Gw9v8JIjdicj4WGeS4z/ww4Wxp+zERVTKCHdWP7Fygw==', country='MADAGASCAR', code='MG', x='0', y='1', area='0', occupied='MG' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAESkYRMsrrsjVXmrf1B7JLb4Pk02pQqC7IWMk5lySso4lxAn0HECeNbBX1J42TuVqWwHih0V6tNcwk/xJkCEspfA==', country='MALAWI', code='MW', x='0', y='1', area='0', occupied='MW' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEQz75M0myYJgCM4N4oaxMeTdwv98KKPTeswcEOah6GfORXgpKQ9bBo6hchEFRaFc0nTNJrwzDBI564LKG7xNATA==', country='MALAYSIA', code='MY', x='3714', y='1', area='0', occupied='MY' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEhDbV8qB0Xm40QuydIULrQf1IaTwegnYfvC5Gu8JOREUAmuiRjpWvbgAKsw0BqWeVTvuxZpNvgmVoa3eY1y2rAg==', country='MALDIVES', code='MV', x='43', y='1', area='0', occupied='MV' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEKnemjZpIizcZ2yduBqDZtM+dOqpCK98uR4Ju0A8RC1xRe50myAI8l8knYcVo/N8R/tTOwW+PbBAKfyYPv5opHw==', country='MALI', code='ML', x='0', y='1', area='0', occupied='ML' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE0cbCU0TYQZswJXTU7zzegsnWM5K9veJrGdBurnYEgx53r7j//7vxJ37RV2JSoavQvmpta8150qs6Z35TclZukg==', country='MALTA', code='MT', x='1790', y='529', area='316', occupied='MT' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEQP9rG1RcxsrM5Ft6Cwm8wIfP1ucYtVDORLNJVhhM+Xq9UcnFiV4to3QvfQUhnP0tD5xOkFBcs/As6pstgSjTyw==', country='MARSHALL ISLANDS', code='MH', x='0', y='1', area='0', occupied='MH' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEA5Xf0vMBoIt+zbb7ocgn/aPidVi4dEHFe5eOMYj4PqPKmJsrjmVguECynep5S71M1EP2fcgO17nnxfOqIzIPqg==', country='MARTINIQUE', code='MQ', x='0', y='1', area='0', occupied='MQ' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE26dU0ZHyA86hYmVEzbSv4ArqtD0+MAKTaqETL1f8HSYroJVPnC7B4pRVmJ84Zb+FloB1vOses7gun6KJwVibqg==', country='MAURITANIA', code='MR', x='0', y='1', area='0', occupied='MR' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEfuXemFGN+C4SD/cyg4+sKQukX3DPeW2M6fF/lEv8NTYkO0hdqgiFP1iRxdq7aro5TxZSbs8CdbDy3KqlA0JUAQ==', country='MAURITIUS', code='MU', x='4407', y='1', area='0', occupied='MU' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEVwJb34r4KU6V1/hTzEyUIbGt06uriYjCLRuBJNfHonKUDopb7aQydYx5Y9MGKlsa5RfeagGP6tqeIfxGEWj1Kg==', country='MAYOTTE', code='YT', x='0', y='1', area='0', occupied='YT' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAESOkyP+QcSM5Y0OZZBF4PLNb1oczT0jHMEJ39j22OF34QhCEArsZu/HzUUiiw2mfbZoIUMpH063LVKUI7/cI1wA==', country='MEXICO', code='MX', x='3919', y='1', area='0', occupied='MX' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEW1DHyikE8TxYBrKklhnmpNrcF9cOb1dOwpKiIQVH2Xf887Lv+Mjfxo0PEYW/NlxLU8xyj9juKi8jl1V0NwLryQ==', country='MICRONESIA', code='FM', x='0', y='1', area='0', occupied='FM' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAExHxgrFJmxdGGVwj/KTEydHh/AVM84gRPIN5lbtO3RF05saZaESUuNX5OGw5aTw2MmQXtw5xyPAObZ6RDGcZIoQ==', country='MOLDOVA', code='MD', x='1925', y='417', area='33000', occupied='MD' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAENESxq+SFa2dX0PTUDgo+xKUelfvs7T7He5OVXoJQ8XGJV7NdS9lh5YhXczG8sZG+hwRGpuy/JjqA8oZ7uxPI/g==', country='MONACO', code='MC', x='407', y='1', area='0', occupied='MC' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEE/6B2cCfhbTkIh5B33znc6vJRXk2SAWIYCBEXGv3wHaW/JGsbD3LmzqPZj/Jwxt4Yk3EPhgg0cP3ceuvB7U5aA==', country='MONGOLIA', code='MN', x='14', y='1', area='0', occupied='MN' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEV9RwV7oH/2vFt4fsHYGHwbQ/jede7mZBZZr9wBmS4K/IInnI8AxzPWE3vqXAgK9VdugPRlN4BCIRVGaD7/CtLA==', country='MONTSERRAT', code='MS', x='0', y='1', area='0', occupied='MS' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEtzjZFKmpdbFUd7LSVhGUDw9cXTK9Q/jbW0fqjgspWF9ox5IgMsN5gx4og4c/O8dTyt3kmt5zGNrEy0rtjeKgVQ==', country='MOROCCO', code='MA', x='344', y='1', area='0', occupied='MA' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE0AW9IIVBKHB+oX9/NjpwL9CbqahqjYfz/s0GfxKdkOc3OKObvTUZ4t4MK5RtLwkZ6RkAXv0mL7WDL1uj5tCaJw==', country='MOZAMBIQUE', code='MZ', x='11', y='1', area='0', occupied='MZ' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEEITSjNAPDRJjUDAVRxiiLXuzF6Kr8LluQMNJUOsVxz6mEtrgBUJ236WENJe19bL57IdDajfbVBb+EVkzjUKkMw==', country='MYANMAR', code='MM', x='0', y='1', area='0', occupied='MM' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEsc7DCAuvslzURCHUINRmppK1E22HUnINbXoZvywfZTMUGF5HjQ4IElcLdq3IIwpV/ECc6l9Ntnw9og5LVuRmpQ==', country='NAMIBIA', code='NA', x='0', y='1', area='0', occupied='NA' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE9/LkTZTG97/9QsGJCPEni3O5Lo5j9KbgZerKLUYLVdikQvTT/kteoObEeXKSNYE8ciyYNWtot6QKwqU8lGzREg==', country='NAURU', code='NR', x='0', y='1', area='0', occupied='NR' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEihhzSXX0BqO/hIJiHqAIRFz1dohGytn44iTbkDmQqhs+5uWyPsZmX2p2HcVVy4AjxlDFptr+6/YkCBtR8mrOew==', country='NEPAL', code='NP', x='27', y='1', area='0', occupied='NP' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEL3FYfnN/thk5EpEBDtHLgeGr19ipauhtpbZ5yd34Yuz7LgFpZBTPP4JkZ7WynIeLSHLAHcpShBv9yefC7Y5idQ==', country='NETHERLANDS', code='NL', x='1700', y='370', area='41850', occupied='NL' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE6XDtQIO0R4wh1QNEiDqnWJgHmCB1lLzM9p160Vu7kz0N84RMNYlyLjEkY/aclUsnsAiQGfXJ8YZvYcu7pnAZlw==', country='NETHERLANDS ANTILLES', code='AN', x='0', y='1', area='0', occupied='AN' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEamS8OKoos1tgED86sUsxMmo91ofvvHCVjF/FK4gGxDlWRRk+s8CqVESKRcNz5J7no30zergYJ7qeL10XbnJmJA==', country='NEW CALEDONIA', code='NC', x='41', y='1', area='0', occupied='NC' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEJVcCxAE0gi1QdeINZef6nJMURmFbTqBFEZ5DaCzplewENbwLCF+pvo60E4bkbROwinoRnhwJcJv8JgMSIgmCRg==', country='NEW ZEALAND', code='NZ', x='262', y='1', area='0', occupied='NZ' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEXsI1S7EfHMfeuUK/ErzXEA32NSiXblelcSzegBJ1OmM6ycPJdfAXX1R7I1FXWadHEF6z3DDseUnJo4x7KMxKFQ==', country='NICARAGUA', code='NI', x='0', y='1', area='0', occupied='NI' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEHFi6i5Bx1aRZR49eaeK4lTJBEz6tgzpWCGmumcvZbKh4ERlBJgmhJS/C1h1F+WIsOS8C7uBtZfI6cwJEiqapaw==', country='NIGER', code='NE', x='0', y='1', area='0', occupied='NE' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEcvWyBKem/jcegYhpRGtb+6yBR1F8XJ72j6uduZ4JI7L69lsxQM2/zRBaIiz3RabA5DyJopI5syX65UzYi5Tqrw==', country='NIGERIA', code='NG', x='107', y='1', area='0', occupied='NG' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEEv55b6Muwl97yIL/pO3YjxSWjNZr3uKVs8+7IgPRUdsaf0iJZ9jDxpG8Bjx5Fgy0dzvtuLghO5AdbP/ti+JQvw==', country='NIUE', code='NU', x='0', y='1', area='0', occupied='NU' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE/aezbE4t2an52cpJuF8ccKf9hzNgWAUzZysI2OJZIQdIgFpcA35JvUdvVXimBzEIaHVFNq7G8RZ1NCXgDHcKjQ==', country='NORFOLK ISLAND', code='NF', x='0', y='1', area='0', occupied='NF' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEC6F7L7EYJPcHGOLJs3rqhYT2e55PSfvcdkDqg/0SZGLGDUHgt3oMWEGotVkmKqxt/O4DxK2x1XosbRE4uqxh6w==', country='NORTHERN MARIANA ISLANDS', code='MP', x='0', y='1', area='0', occupied='MP' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEnmvqN8auc/2PR3hOc9LvyUtvRz4Yojk/Vswj1bXS7/x7jF7U6R4Bnsk0mBY5bKKYJttzwN+nmArvmdubra8HIA==', country='NORWAY', code='NO', x='1742', y='281', area='323000', occupied='NO' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEECAhLB8zY+H57sz9ujZ9H9nzqqnmNqxg40+VDySO3ItV1iD/RIySGU+UvIfce/jtZDdCGqTar1rLHam/ALmvsg==', country='OMAN', code='OM', x='273', y='1', area='0', occupied='OM' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEXQe/JOkvylnoBBel0sDRmZ8Hw29ZYgHbekeVKYC/zztzB1JPZ8KYWlqzXcbnRbGVhF9GVAkq9nxWLLdiw6nNCQ==', country='PAKISTAN', code='PK', x='1006', y='1', area='0', occupied='PK' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEnWw0JCfbROP+YwSjpz4wd7T86U0DOl0R+UcfbG+GKbgLkQfbX4xEkXA5OK0n50UOvKAA29VJ+LgJ8O6SemSTpw==', country='PALAU', code='PW', x='0', y='1', area='0', occupied='PW' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEXAwdcWipvQQv/py69UH2En2uEsIOdWrWFcgIx5sVC/I3EJCsOgmx1stN0GvrGMNGPqx7XMX2PL9PSPR3YxcKwA==', country='PALESTINIAN TERRITORY', code='PS', x='13', y='1', area='0', occupied='PS' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEjsxrq3jeKck1M3naqrSh/G7GrHHjXm4MlKYYR1n61bG0qPDVWmHTsvnAHcjSnCiwyvZmOEooTgPdKzLkRdOvSQ==', country='PANAMA', code='PA', x='184', y='1', area='0', occupied='PA' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE/vc+We4PtmDNTsW9+4YSy0l+9OeZN0Gr1Z04q9QG6B9LNAY91l/YTNWsmZMoCA2ijuPvTYreEByvOclUQlEKsw==', country='PAPUA NEW GUINEA', code='PG', x='0', y='1', area='0', occupied='PG' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEPyle3yxjAjvhOtA/hBBKV+5Wzs7am/3Rwcup7AxJ7C3Uht0SYqk1wAFKHhFlzBjxoUNY8KOwWkkQZ11kTcenlA==', country='PARAGUAY', code='PY', x='388', y='1', area='0', occupied='PY' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEeVO8nzS/fj4z5CDKv188rKRLnS7bNg34mYCwCs07fRX0G5z9S/u4jvKFcgm0ZgKIg47iW1h3Sbtuyu/qhGGSag==', country='PERU', code='PE', x='906', y='1', area='0', occupied='PE' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAExz2zJNP6alL4aCxg0oyIntfypdqK8u+vilc8fMj1MlEtv6HSYQwACupcaWuD7G0m1v6zGHoGqCvUKilyQegSzQ==', country='PHILIPPINES', code='PH', x='4322', y='1', area='0', occupied='PH' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE8o3QG4WacoFSsHv0P1rsvixnWBzq2QYE1XUtJiJSqgPJeUIdq7uDnNbsXxIIwcNHszdTA33tTiWFsv3pJXwadA==', country='PITCAIRN', code='PN', x='0', y='1', area='0', occupied='PN' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAExGxh1dBTj+tjN9rT6n5aeToBmA41FeC+LM636O0J7VG5WMfNcrHU8d6QznjW9uM3HMHskljxXgR03rfBeQPNzw==', country='POLAND', code='PL', x='1838', y='370', area='312000', occupied='PL' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE53e+8L9epREc/71jO2ZCl89EkAjJDziqwv3uF6ODV0Zdv9M6wIihRYCl9QM/IjG+wJW8y6TYhyUi1fvftEFMLw==', country='PORTUGAL', code='PT', x='1570', y='490', area='92000', occupied='PT' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAER/cHt2chCtaiQ3mFLx9l2e7nzjhAlD5+l/YYaJzPmBeKlPdhIFItWXEsPXx7x3I6wnTpj8XGoXg8j8kARUdytw==', country='PUERTO RICO', code='PR', x='42', y='1', area='0', occupied='PR' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEIf49h7Ls6aZVrIo/BjSXlmzc+pM56UT6LcaOousJiTOGe7Q9JLuGyXHT70i4LtrJCJ1RgRVD2JaaWTVWKLku5A==', country='QATAR', code='QA', x='350', y='1', area='0', occupied='QA' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEGuAeNp74FWOuzglmwczQLlHJPY2G895uHgQluiP7f0F5BCHw64j/WlRhHhobtSl/lAtKDRWu8rpf5RG2pVcy+Q==', country='REUNION', code='RE', x='14', y='1', area='0', occupied='RE' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEfrOZfF/uuSIt/xIvpmXH3a0A++nXrS4Mw1pIpwwYI/9PRHiXTX0LDGx4IY9lf6oHcQpZLMZq9eFfciOoPW1dDQ==', country='ROMANIA', code='RO', x='1890', y='430', area='238000', occupied='RO' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEouR36rqcYyt1nCgsjglIf3RICstkU3UoE4fD3X4vX+nLYS40PVkwmjpwQkpUfrKwbkDT+sUR555oTOC2o8Pn2Q==', country='RUSSIA', code='RU', x='2600', y='270', area='17000000', occupied='RU' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEh+O2elM5AQDStf5Hmu6McAI1a0LW4xRCOqiDz/vDCrUmWbgalESzqglIgVOPW7d9M60nnt9c5aWSjMlVChp69A==', country='RWANDA', code='RW', x='0', y='1', area='0', occupied='RW' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEcLUqJ0/BIMpnPvhDMDlKNipeNImAcznwQa7sYTTX34oTdJ11ikiwzfJDtxtC8aQLLcOoAhAb226Myuyne+OwKA==', country='SAINT HELENA', code='SH', x='3472', y='1', area='0', occupied='SH' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE/HhXSG5gVS/77b7LfN8GAuIvxybAV2aeYv20eb12EG8P/jrLYbHfl01+ZV65JebthPt+m46Q1gm3BpRCdkxZFA==', country='SAINT KITTS AND NEVIS', code='KN', x='0', y='1', area='0', occupied='KN' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEVI45Lre4Fb09KK03/HN/N1DnZdjPX1HadA/KuFPRGBT6dqfzefnUJ08uovgKw/oqAnsPu3FtNCCnMSHEDC0ASg==', country='SAINT LUCIA', code='LC', x='11329', y='1', area='0', occupied='LC' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEve05Fc2pQYTRibmhnHdWci8Y/1sstCijwdZCZeIuOaXdXSw9xbaufBToRyzqgyIm/VGJq58wALVMNq2igwpc8A==', country='SAINT PIERRE AND MIQUELON', code='PM', x='30046', y='1', area='0', occupied='PM' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE4EKqnB2MXMKTUUSMS1juxGI75YmyIt/6lV2BU9j01exEmwsxZCnFOhfO/NCKqmGlC6v/xXmbT7GDd7Qw/6hfXw==', country='SAINT VINCENT AND THE GRENADIN', code='VC', x='0', y='1', area='0', occupied='VC' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEJLPD2QGA18xSaPJ0L8MRbwVjo65PRWoU0cVOhLFFBvt8MfgHNY1lCUnvadUDqOBiqQOv5lKKPnJ1A5iEs2Ntew==', country='SAMOA', code='WS', x='0', y='1', area='0', occupied='WS' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEmqR2MhpyDs/+84aJi89DvBlLKutYT+l65Pq+OFf5kmQAt6ovnO0QtkBQZpDQY9I1aT0s48nuG1b64/ug1WYztw==', country='SAN MARINO', code='SM', x='0', y='1', area='0', occupied='SM' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAELGkrFDSE+ONqbIJ4+c0/KQimV7kQqQRNe5hf6OSMraT7fiymnH/s/Qrzc2/4wIg/ye4c/FpL3jEuIE5tw8oykA==', country='SAO TOME AND PRINCIPE', code='ST', x='0', y='1', area='0', occupied='ST' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEKUu1uuu/yN/zIb86lIsWX2KByM4Xa9b9RNjWG4WPXcgIiEHgTjFGMGwIrYTGbAIXzT4TUdDeKGvE4eDbcBgj7g==', country='SAUDI ARABIA', code='SA', x='135', y='1', area='0', occupied='SA' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE1fYXqOKE+HMk7N1Db9qPzhfI1ZqSJqRuidX5O8RGQm/u2pTqxmrp7CT2wTF8NebmD830YhZnZ3Y4GAf3zqqLGA==', country='SENEGAL', code='SN', x='0', y='1', area='0', occupied='SN' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEBViOu8QdptMOIsTJWMXMmCcduRLsSka3rY/XDWcdnWTzvNFXh8o5chG8WG8sRkFF4ZTdjme+bskK5g8sjLqPCQ==', country='SERBIA', code='RS', x='1850', y='448', area='88000', occupied='RS' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE+0rZmEZbPAKi/XRDkuTBeWcXZsWuKmuxWkSR9Xpm5KQp58ElIpUW+/YvHj21JJpgUDdp8I8qxQvM3K7nPXX1XA==', country='SEYCHELLES', code='SC', x='0', y='1', area='0', occupied='SC' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEXOVylreDY/NUlLu8ujRe64/M9vPAJZJrcxtzeejV1tomo8TTdOgF+t3B2bJ4c4UPODCioMOQ6F1gmMAJpWFYtQ==', country='SIERRA LEONE', code='SL', x='0', y='1', area='0', occupied='SL' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE3+HTbVdwRNRwiBCUJ9MLr0kGKhDWw+RuX4HdvTvVZznVICrGJ9b3YlB4mta0QbVlW59lS6fHbluhvOziIQ4D+A==', country='SINGAPORE', code='SG', x='781', y='1', area='0', occupied='SG' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEiCb9hnlKMloM7NrPioGCwDhb6NHbGJmEsl+KB7XFpjb9uvNY4Z0BOIJ2EdY3gOK0ufjD8B0ZivomT7Iaud9vPA==', country='SLOVAKIA', code='SK', x='1839', y='403', area='49000', occupied='SK' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEdOGNk5J8jT/66TNIPvCr3E0oz4mWGk+6SqZBFhYYsQQFrZ09o8dbVCXO7939wtNZKm4zGmRM56Rrc7yUJvwb9A==', country='SLOVENIA', code='SI', x='1796', y='428', area='20000', occupied='SI' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEvhDkK2Ydiaoewu4vE+HKx0iH/LgTSMNHqFUaOQ3JbXAJ/Nma9Hg3RD1AerZRwhelF+L4tCm3/bix6bRYCzwc+A==', country='SOLOMON ISLANDS', code='SB', x='0', y='1', area='0', occupied='SB' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEh9NtC8So1dxgcv3rdqP8+L+7As1EBPdMkqSvj8Hu7q+PEXEiF8rNSoV3skoXWpAXoSMIWR4nrh7O5Ztv/FMdjw==', country='SOMALIA', code='SO', x='0', y='1', area='0', occupied='SO' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEV7nCo5iF3sOJL6J9IudOspho9XnxsVCw7XHzKwzQ6Wm65gB5YkycI1TL8Y4X5rxxeOSNjntNWdHnx+v4XRAYxQ==', country='SOUTH AFRICA', code='ZA', x='712', y='1', area='0', occupied='ZA' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEYLbTwPxYugaBDDegxgVxpD7Jw1oKXw9FsQjMFAQkdk2eDXxEXlSpmt0M0sndabxRopCtCrZH0aNXbQDybbX7zg==', country='SOUTH GEORGIA AND THE SOUTH SA', code='GS', x='0', y='1', area='0', occupied='GS' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEypUGQJc2NG70EmrYtZJLHj1ivHyauADgvSvZbTaregiwmiuScEPBQAJ11Ekr6exDDFUi7AuUWZ+oShSBLPDsuA==', country='SPAIN', code='ES', x='1600', y='480', area='505000', occupied='ES' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEoHvQYmQXQPBo1NuDW0At6G4y4LeqFDT7zR132gluibBv/7tEd8i6SVan1ffvdHjAZlruhCL1y7TRe4tLjINHEw==', country='SRI LANKA', code='LK', x='68', y='1', area='0', occupied='LK' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEQS+i6OM8ZEbDt5MKETxZE9OWag/mXSeu22oJysTYMIG8rJyVVnLUdPyx3rwR0WWx6dS7Ji9UTUUn/4wXA8oPWw==', country='SUDAN', code='SD', x='0', y='1', area='0', occupied='SD' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEcTBscX8XLWSw56uoJnyrZSmOCky3ADcDKCHmTkrHkRvoVVpQ8RisAc80GLMwnloUrGR4JchCzCBqotZcCwsk5w==', country='SURINAME', code='SR', x='14', y='1', area='0', occupied='SR' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEFpqEzSXY7ZfTFi7ajs6tCExY7OozLNUh77pPSnh7+sgYeukcRMYP4c65O44mts2YSDSKztyxnjNLkHW4f8I6Rw==', country='SVALBARD AND JAN MAYEN ISLANDS', code='SJ', x='0', y='1', area='0', occupied='SJ' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEmAoChknOiLezkCifYHxk3W7/8kjAU5ewDnE37DZmi2aAnWVGiVIviWHZFpg8tMQmwRosPAgcEYV+D2qA7O3Maw==', country='SWAZILAND', code='SZ', x='170', y='1', area='0', occupied='SZ' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEEAwviUsF5PK93+Cpr5YbHks8ga3w3c0/VTQiaoSaK0QJd4DktJF70TfuJvd39Ii9k+d0GjnL31F857iTuJJGEQ==', country='SWEDEN', code='SE', x='1790', y='290', area='450000', occupied='SE' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEqsChQEwiQ6t+IQ3wjiaRjmi+llX3UfGx+xKHnoyKSIaRVIE2OB3A8+0BwIlA71sWolOYPanxCQBKdVb1ogAGeQ==', country='SWITZERLAND', code='CH', x='1730', y='420', area='41000', occupied='CH' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEZaYnJIMYM56gnZzm2fIMPnHrd3Oqpxc8yCJM0lKQjbZAvbQlV9Xw/3aitZo1ViEvRQPzvQsDF8fVqg9sCJoqDQ==', country='SYRIA', code='SY', x='14', y='1', area='0', occupied='SY' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEFOu9SqekICFoQUldIyi7mbzlz7V5F2d2EK0d7twwH/Q4RGqikh2zB9922OKRnN9tWR9SHfaa41E+AafS9/F7cQ==', country='TAIWAN', code='TW', x='557', y='1', area='0', occupied='TW' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEMobBOUqnd+d9iU9xPehVcgLaFWbPvngk3u7wd3geMDPLg0fAYiJPUE/UJOcBm4xZgtPJQpYh4sH/x0WS+ZJ+ow==', country='TAJIKISTAN', code='TJ', x='11', y='1', area='0', occupied='TJ' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE3sEhP2C5T40c4t7azaNT3//N1WW8JTI/iAJtCoHh6tRJJofydER/soGTWNhaIwmvTuYN6YmypqN4ad9JqCQJuw==', country='TANZANIA', code='TZ', x='11', y='1', area='0', occupied='TZ' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE+NfWlZvnv1rHl+slmILOnPtmf+FjzmDpnluozTy7/Apnq0XaPaJOwd6c9NbEuCKIbBX42WN6cyxxvpsJZAu8gQ==', country='THAILAND', code='TH', x='2422', y='1', area='0', occupied='TH' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE3I4a8rAQZLbOAZ5G0lbavPc6GTGr5zXRa4qSWGE3LYpfcDAOz6S/ETDP8e2UXe2WhB1GloCs1g3YvfAX4Y8Odw==', country='TIMOR-LESTE', code='TL', x='0', y='1', area='0', occupied='TL' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE2b0LHZ/BzwrDOMxUfDd7Bu+a4pzk88jy5Kt7uCKtRcLmp909fNRQUsNrM6ri0g/8rrQJJwd0bH6QwJqRW1035g==', country='TOGO', code='TG', x='0', y='1', area='0', occupied='TG' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEwYQA/fujJ9pDg1OUckxMcWohv87K7AiXSHjVAN3+ikMzdFh5RMrl3xc6Py7vrcbDJmwqpE6Mq3PwUiXyfxrpbQ==', country='TOKELAU', code='TK', x='0', y='1', area='0', occupied='TK' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAERk5K0J/JubkFZDuCZdboRSS2ld54znPN/91MlC0MbmT8LWPowtH92TL4ajKrDLSJqwIfiRm1aiU5Qw5vKBHE2w==', country='TONGA', code='TO', x='0', y='1', area='0', occupied='TO' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEvwP6ZAkkAdPVsW5yEAhLkJnAoWXOKvUocQEaKmaEuiXWM/aXT978y0+UvJVuljCSvJxFGJhcF78eF4s5vnNVnQ==', country='TRINIDAD AND TOBAGO', code='TT', x='0', y='1', area='0', occupied='TT' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEsYfx1J8cUNDe/FP1SJ6y3NneocKv9bdR4qeCFwLlYLMw1qEQSZK3LQxj0v0j0PbJw1fQxWh5D8g5YZCJ+zchxQ==', country='TUNISIA', code='TN', x='121', y='1', area='0', occupied='TN' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAES26oWmcmBUPjiUM8ocv+lcnADdfOTkFugscImTIFqYrMOlio1EetmSHwAjG73qBJlM7sCFtu9f9SkX8ruDNKNw==', country='TURKEY', code='TR', x='2000', y='500', area='783000', occupied='TR' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAErOkad+u5QzGjY5Ul2Rxv+QRtEORVfjQ77kHvO7hnGAUsEjU8SPD7FHfKduwWvepYOtB7e9xW+Qrdo1AQnaSuUg==', country='TURKMENISTAN', code='TM', x='0', y='1', area='0', occupied='TM' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE8L/qkdJhjM3uCSE0skHwaWEqxZu9iVDlAZt/v1w/OZpnnhsxrgmSeEMwA6CT/q6qCRQeCVNQzKEVSBsU9CuOZw==', country='TURKS AND CAICOS ISLANDS', code='TC', x='0', y='1', area='0', occupied='TC' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE4SyZYn0hzw4EnLWZyOUTMAae1hb5u5zy1NxEw2MR3nmHs5p0gcSjDoCs6ByFARGNzFwvjdjR27Uc9Sc5c78CbQ==', country='TUVALU', code='TV', x='0', y='1', area='0', occupied='TV' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE81pVA7WZ+R3bEZPTSlzzUycOQs60KZC8Dw2AmxWabgSK63d2oZCkPCGli9Iiqcl0otGwDoQkPdlzhooUpg/NFQ==', country='UGANDA', code='UG', x='0', y='1', area='0', occupied='UG' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEKm59RSxZNViPHV2ly1HFo4ta8IZ4HgER/2DDaLwu0O6yWwiMrqvkY/JnIOXi53iBnwm3B7aFmCkK/X7afM/f5w==', country='UKRAINE', code='UA', x='1950', y='400', area='0', occupied='UA' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEFQFBn0ypBT9RPLqknkcnzw9yLCy+ZxXSmIRTXMpytzYO67P+SnGiEaH9mHAApBDEvMMEmstCXFKOqC+b78VNDw==', country='UNITED ARAB EMIRATES', code='AE', x='0', y='1', area='0', occupied='AE' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEoLEo06v9Le69IogrcITSCtACSJBeGIEe7pbCdS0l6CjEESxbU1kPtKWUZvd4m35tEsf91l8KTcGJn2/ENxQP3Q==', country='UNITED KINGDOM', code='GB', x='1630', y='365', area='243000', occupied='GB' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE8x++GRC5LQ1XH2sg0kbMQkGEwnmJFffK4qLFQLVpH7Avv2MIoI4L18w2/FwMMxIo14NKKJ4b4+tSM4ES60eTkQ==', country='UNITED STATES', code='US', x='14555', y='1', area='0', occupied='US' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEVt53r0jpg6hRJgSgGeP1UCopV/JHmvyZkp8pW32Gj0BmSgVab+vPQsXq3aZsCoVEXeWJvs7Pvp/ZnSLXIwwAMw==', country='UNITED STATES MINOR OUTLYING I', code='UM', x='0', y='1', area='0', occupied='UM' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAETuMZA4y4/TRPWgBRAsSvVqTNtZMbe2jgWnXshznygWhBPTSd80239Q1lJ3LUYg/lK0PBqEpu+nsBuQeXHmXlGA==', country='URUGUAY', code='UY', x='245', y='1', area='0', occupied='UY' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAET3zzONr9zzoOGYFQnyaJ+0Hemd7obh/0SCN0JfTJEVv/IhYt2/XP5PzeQyKGyJsqGCVtzwIfAzsh9luV0/YVIQ==', country='UZBEKISTAN', code='UZ', x='11', y='1', area='0', occupied='UZ' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEHVx9bYWll5xGRh6i6DvJ/I5A13l5IZMAAJRBWyrAKi6UzNoUfLYdevYRzf4O+Fz+2Yjig+nPFwdXYICp3XDiqg==', country='VANUATU', code='VU', x='0', y='1', area='0', occupied='VU' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE6CMveXT90/EfFGHioDgmikt+tSM8a0lVEfKWcN8FKNgk8fsdjvdieEIXT0jJtI9ri3S4KC9EynAyoQRbN1Oaxg==', country='VATICAN CITY STATE', code='VA', x='1770', y='470', area='1', occupied='VA' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE5E+7kaf8WoPyWjmJ2fd+c2xfCcQLkRNc720jj6cH5BefBJ9Y7eAybNF+rJxfMqJm0d3QOFj8aWiQjDVPkG8iuQ==', country='VENEZUELA', code='VE', x='5642', y='1', area='0', occupied='VE' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEy/KPlJWYC9QJxLqb54SdkRZ+OBg4ZPFzaj+eIwcBC2NJVC0yLiUhzgSH7phMfz6FhLXm5TWE+p6T+TW71GPsFQ==', country='VIETNAM', code='VN', x='2653', y='1', area='0', occupied='VN' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEGd4bQg91ZUKNsjms492JNVvSCMq4zCovavU9IUdd0MWn944ElRTqkLPOykfYuGLeqaetOfNFZRoItqJwmzM1zw==', country='VIRGIN ISLANDS', code='VG', x='5715', y='1', area='0', occupied='VG' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEZUDMCSGcx28t6NZduF374v462AK4lA++0YE31YEwV8OseX3+xK7w1BvL/NyEnh+9nZIrMV91eRLyuh6WEzPMHA==', country='VIRGIN ISLANDS', code='VI', x='0', y='1', area='0', occupied='VI' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEdOuIv7geKgtY/+qd37ZuCSh8G469aJnCNLp703o3NckNxTvzrofYqIp++Sg5TL6Pj52REJzMg+AQeW1kJl9a9Q==', country='WALLIS AND FUTUNA ISLANDS', code='WF', x='0', y='1', area='0', occupied='WF' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEaZh7Hb508clSRz3W5MiRugZNWkfa41o+BJaHeXsYaOdsLgqzj8qErZNfTLLeFIRc2OtUXhF10zh++/5m5JM5aw==', country='WESTERN SAHARA', code='EH', x='0', y='1', area='0', occupied='EH' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEwYZ3/xiTlQVgWT4ipBdg5Aj2hSqoi7Fvu22VBTPghmfGKFiLFvdtA8PDRTo4Clh6iFG/D0Pin8UAA92SXm/VkQ==', country='YEMEN', code='YE', x='23', y='1', area='0', occupied='YE' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEYVWxgS5vo4IX6Q4Px9xpjVMXSccGr+oUniUm9znoRG9yvbgTVm7ScLPy0T+pIgYIKoTS4L1ZxIe03GYgSjoGhA==', country='ZAMBIA', code='ZM', x='0', y='1', area='0', occupied='ZM' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEg2gm3JGklXZZ4oAe1DG8a6YvUK8EEOsQsZ3WmPHaH1YkA7ni/6WjkzpyC5bScFYPA2l6ZDquO1zTx8PZZI2AZA==', country='ZIMBABWE', code='ZW', x='0', y='1', area='0', occupied='ZW' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEnjhIEv1jVZMtZiO+WoTvFfU2gHo748+4DW9gVloCxBLHlzWEwSw6yB0HYWVBvx4RoNpGsG2y9MoL8W5DMQwTNQ==', country='MONTENEGRO', code='ME', x='1834', y='461', area='13000', occupied='ME' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEEzEwNoyNoc9sRB4FRPY5IKEeZEImrZJD065taKPi6aihnl0DXVNYaaqq3fL6lIOTrTd2O/sW/bCD9IFJfayGxQ==', country='REPUBLIC Of CONGO', code='RC', x='0', y='1', area='0', occupied='RC' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAERMARlXN5wqNq8n4ttZ3weWcXE9TqaQTAXKJoW1QguukRGf4ZqPhCPKuc2fEfx9V9BOghGX8L4SIq4rrK7k66LA==', country='BURMA', code='BU', x='0', y='1', area='0', occupied='BU' ");

   }
}
