package chainrepublik.kernel.net_stat.tables;

import chainrepublik.kernel.UTILS;
import chainrepublik.kernel.net_stat.CTable;

public class CCountries extends CTable
{
   public CCountries()
   {
       super("countries");
   }
   
   public void create() throws Exception
   {
        if (!this.tableExist("countries"))
        {
            // Status
            System.out.print("Creating table countries...");
            
            // Create
                    UTILS.DB.executeUpdate("CREATE TABLE countries (ID BIGINT(20) AUTO_INCREMENT PRIMARY KEY, "
                                                         + "adr VARCHAR(250) NOT NULL DEFAULT '', "
                                                         + "code VARCHAR(5) NOT NULL DEFAULT '', "
                                                         + "country VARCHAR(50) NOT NULL DEFAULT '', "
                                                         + "x BIGINT(20) NOT NULL DEFAULT 0, "
                                                         + "y BIGINT(20) NOT NULL DEFAULT 0, "
                                                         + "occupied VARCHAR(5) NOT NULL DEFAULT '', "
                                                         + "private VARCHAR(5) NOT NULL DEFAULT 'NO', "
                                                         + "owner VARCHAR(250) NOT NULL DEFAULT '', "
                                                         + "area BIGINT(20) NOT NULL DEFAULT 0)");
           
           // Indexes
            UTILS.DB.executeUpdate("CREATE UNIQUE INDEX countries_code ON countries(code)");
            UTILS.DB.executeUpdate("CREATE INDEX countries_occupied ON countries(occupied)");
            UTILS.DB.executeUpdate("CREATE INDEX countries_private ON countries(private)");
           
           // Populate
           if (!this.reorg)
              this.populate();
           
           // Confirm
           System.out.println("Done.");
        }
   }   
   
   public void reorganize(long block, String chk_hash) throws Exception
    {
       // Load checkpoint
       loadCheckpoint(chk_hash);
    }
   
   public void populate() throws Exception
   {
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEwY2LDnb/4Xfa2CG7dhIp+9oq5m9/ADvELW9IUgbQNp/F6zM2etAZf1JceuLstlxSoZLZ2nOX3E4ohjZmvbiqzw==', private='YES', owner='default', country='AFGHANISTAN', code='AF', x='2964', y='1047', area='652000', occupied='AF' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEn9t/OjiQ275OiaVX6ASfq/lTL0vH+mceuPT6Fd6A3JDwAEyzuGh0eh1ef0+EhV2I+qn0//A85NtziHSCUeYnVQ==', private='NO', owner='default', country='ALBANIA', code='AL', x='2392', y='912', area='28000', occupied='AL' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEh223/yLaVDwt0KHRbETRW7tQQx4nqtg4+8bpYxpgyu1462jpxEiXmWQ9tqufGx8V9s8JVhrrkaseiX7L9hocTg==', private='YES', owner='default', country='ALGERIA', code='DZ', x='2171', y='1140', area='2381000', occupied='DZ' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAERITd7+5w+6skIj3crdrBOAHWykoM1Vn3vyf1+CIfETuWHysNJW5kgGGA7aVPlo7JYSyIwILD6MS+ApRZBrRJYQ==', private='YES', owner='default', country='ANDORRA', code='AD', x='2171', y='880', area='468', occupied='AD' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAErivtW005L4I/TMGRBa+fJfU86GODyF4Vdj14z9YRucbDx1hysIMeb/W6EowFA/KomGNwrbRUJ9ATnBJNrDglag==', private='YES', owner='default', country='ANGOLA', code='AO', x='2361', y='1887', area='1246000', occupied='AO' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE3GK9/oHlRm1XxqbWB7xIXsQdvuFuTT6HnKhLgGhMiEJZxWPw8JhYiVKkAqdNg0Fgrz4XGk6mFktjoo1ew778Cw==', private='YES', owner='default', country='ANTIGUA AND BARBUDA', code='AG', x='1379', y='1393', area='442', occupied='AG' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEPqELrzOT614kOvOaQTDl/vBkoyKqaGMRoH4oyd3Zjlb94aTr2Qp2SB7CPg8dCcgXF78QZ6xaN/Ea9HGn+lPmkw==', private='NO', owner='default', country='ARGENTINA', code='AR', x='1310', y='1972', area='2780000', occupied='AR' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAET3hLzm56073U++ygcC46vSkN1qzTAqzwsY51nDuvTnrw4mzvEkr4paQW//sTeAaxxhmYY3UxoPW0EWu+ll5DUA==', private='YES', owner='default', country='ARMENIA', code='AM', x='2707', y='920', area='30000', occupied='AM' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAERMoCKcvcwyYdzDNHT48xaO5EuFVZSlp+ECulyzF5faARwC0VO/6BVGPKMHJl5nYThNj6l1Q858vNuvoU08LY0w==', private='NO', owner='default', country='AUSTRALIA', code='AU', x='3741', y='1879', area='7600000', occupied='AU' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEnAMIzfvHU8P06Y6VJdlCb7hrWtoPuvsxT+93B6wD4T9ZAuN1XDOuuEQmIyQ8j72kEB7uJO4PY0yxhPaNcaDjTA==', private='NO', owner='default', country='AUSTRIA', code='AT', x='2327', y='785', area='83000', occupied='AT' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE1cGoQ8CEb5zT57830erLZ/66dP60dzvIA+eYPekM2UvEvVbzPWI65jOzS/u6JaLmzUEtbBSdHJiI4RQx5YOruw==', private='YES', owner='default', country='AZERBAIJAN', code='AZ', x='2700', y='989', area='86000', occupied='AZ' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEm05SMZ/YtTC+3W+3Nchhdn6FQ8QE6IVbN0VcWIU2uT+BGc5qRsDGHdwt+YmxnzJnq7FvwVcUCXr7IDYn0spjGQ==', private='YES', owner='default', country='BAHAMAS', code='BS', x='1247', y='1159', area='14000', occupied='BS' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEVVdmSjVIDh0cn+7UGpQe8xRAkKqCKRUOrAh0siv7/AkS0bgXMPggqHuRZOFgSE4TN0PE7OBQHHV1kS9xQho5oA==', private='YES', owner='default', country='BAHRAIN', code='BH', x='2751', y='1182', area='765', occupied='BH' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEIHQhOQmdi2G0eKRXb2NENluuWOC+SifMMIFr82Wzsb77wE5Kfku5JGYOAZ4YobmkMOIhBQwMWZpMcJziAk5qdg==', private='NO', owner='default', country='BANGLADESH', code='BD', x='3222', y='1200', area='147000', occupied='BD' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE9c6TKjyKemN5Gpk5qR0RmOhbmxlyAAdpvVuRPKLM2rheLvotamTOfnSs6+g0suIKC9fkAiIjsv/YHZs2WvLnSA==', private='YES', owner='default', country='BARBADOS', code='BB', x='1449', y='1350', area='430', occupied='BB' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE7V6aSglivqzzER2OyDbsB2JHjjjuIAHVWcaX0fc3tLO4EN3RiyxhH3jWv9BkHdhqbjhofaSXxTBsrggCC8rXIQ==', private='NO', owner='default', country='BELARUS', code='BY', x='2500', y='680', area='207000', occupied='BY' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEC9/+bkVVa4oOETWOnF4IwK0AYPvpanbqONJylxDlJd0SVyTSWpGlmEZp+ZgH4k4riWJOdMUwPfyy9fz5aTXL0Q==', private='NO', owner='default', country='BELGIUM', code='BE', x='2210', y='732', area='30528', occupied='BE' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEJP5BU4IL3uyDgScY47drlQE5fnyChZHP4WbxaLLA2oIiCikhWL013B3u0d4HIFj+FjyxETUM0+66phzJAVAHJw==', private='YES', owner='default', country='BELIZE', code='BZ', x='1102', y='1294', area='23000', occupied='BZ' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEhRLEweokVpSJpwS8o2VkvuSfpHQvquWYdJq2g8+ZEf/kwWw8Fcj1U5w8ozEK0IeVfu7d40dMqMm4E5Wao25lsQ==', private='YES', owner='default', country='BENIN', code='BJ', x='2187', y='1380', area='115000', occupied='BJ' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE/kQn6JpypiRe2r1LJv7Vrd4jUCJnU6i9uATkI0N45BG9Bkdc62jwn6/xv9yhEAxLDPdyJUROmrlyzIdPk1U2UA==', private='YES', owner='default', country='BHUTAN', code='BT', x='3220', y='1158', area='39000', occupied='BT' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEQezs7x1mjyoz/j3ptVjbyuHslm7p5WUM9HnLWdmBMIeIDzns06pS8E9k4S87Na8/JqZcLVbokpj057Sv5/0Mow==', private='YES', owner='default', country='BOLIVIA', code='BO', x='1391', y='1710', area='1100000', occupied='BO' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE9IlC7FgeYS4SaovwCpapxiPA9bcYMpk1EtIIO6DVaw3Rr1crop90lwhgoUUCDL4aJUaABSVdZ6F5sgEr5OKZJw==', private='YES', owner='default', country='BOSNIA AND HERZEGOWINA', code='BA', x='2371', y='853', area='51000', occupied='BA' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEW5BwK2Zb08Mjt4XNwnw2Z+EfRypWr+5RYMEB9DK68YBynNxnE11vw9NRXgJTDOgOnOQ/nu/Mrj/8O+CN4Epefg==', private='YES', owner='default', country='BOTSWANA', code='BW', x='2442', y='1776', area='581000', occupied='BW' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEmg0G6DJIpenL79hJiDkto8IzUVuZ9DjWepgVEMEHxPc8VOrUG9imKrn3Y71sSZNRkYh1sFIa6I1eE1HqtK5O+Q==', private='NO', owner='default', country='BRAZIL', code='BR', x='1500', y='1650', area='8500000', occupied='BR' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEFXAz4t+koLLoHO8Pl7AIoJu+AALUOPsi4Gd3Yg3GpjzRhC1eFUT/cakroy1UspQZapiNV0/EbnEcSnX22YVXwA==', private='YES', owner='default', country='BRUNEI DARUSSALAM', code='BN', x='3538', y='1454', area='5765', occupied='BN' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEpcQqDa3ebGcut2aBROEY9XYhWCCIM/NNG0/wxqjLx9gf/jedFA5lQgpLfAofNnd9oc4ruQ0gG8dTE3AzqOtl2Q==', private='NO', owner='default', country='BULGARIA', code='BG', x='2457', y='882', area='110000', occupied='BG' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEE2PA415sG2lmUdS+lMxWoBj8CK4VTYhyUnvK/ouEnJjXZmgRGDHrYH7Z+n5aKR0tOH8GeCF1dxOlLWHNM7kpTA==', private='YES', owner='default', country='BURKINA FASO', code='BF', x='2140', y='1358', area='274000', occupied='BF' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE3AC+PLtj+f1dE4QOrJzXWpGe3yNlcRfpOizWooxXyQStLYbxZzLa5iYSigrqAY+nTfJFs6oKf3lQIypqbH4B8g==', private='YES', owner='default', country='BURUNDI', code='BI', x='2514', y='1545', area='28000', occupied='BI' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEBVMFdFalN4Uyvuy9pKkDY4FZxlSOrtZ1tA36ka5OpVyuXUjqYETgc9bwwNSxTKWj8gXxNJsE3h02ZSUWl+JFvA==', private='YES', owner='default', country='CAMBODIA', code='KH', x='3418', y='1350', area='181000', occupied='KH' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAERuJaOZu+FJC09M4tmceUQ1fUUBikWr6lDjbQqOhMBCs5JlgDb1r5IO0Sim6EcFBKgVZ3ApNmP2s6VH1rPaWGeQ==', private='YES', owner='default', country='CAMEROON', code='CM', x='2300', y='1450', area='475000', occupied='CM' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEFL+MOSl/UHok39CBtE/azKHdHBM2jUOAe7zrIRSIDA6N3yFGOyA5pNxX5TEmZzyXj5/de30/Gy8vzBDeuJl+5g==', private='NO', owner='default', country='CANADA', code='CA', x='1000', y='500', area='10000000', occupied='CA' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEDv9iG0KLjDCPYkWAM8B8Zkl0UWa0W9xAFr8/bZSZm/uxQa4+DfkG+gb+PaLg0FJZppNzXCdPuvb9asMGR62zzA==', private='YES', owner='default', country='CAPE VERDE', code='CV', x='1864', y='1300', area='4000', occupied='CV' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEtojNw6bkwB2luTzHs64dQBFuqRgKMTMDN1+EJAZZso84UYskqA0MsfZgiNnt6RwVtvujQOszbCRccXfYWm7bJQ==', private='YES', owner='default', country='CENTRAL AFRICAN REPUBLIC', code='CF', x='2400', y='1450', area='622000', occupied='CF' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAExsOrFIa8ML8o0NpRl+laiSX9kSlQByb1uJYRnpKteFNL98gM8nJPVey0HSCxNRnmHX3Usxl22wI9es+e1yyhDw==', private='YES', owner='default', country='CHAD', code='TD', x='2400', y='1300', area='1280000', occupied='TD' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEHTZp3BskBYX6A0Tu51giPyOBrx+YtWUQ83CtHbTyu4L66FfIoipUNvyAIQTLY7Z3oTpKfPb2Gm0ZHTF/km5PWQ==', private='YES', owner='default', country='CHILE', code='CL', x='1325', y='1991', area='756000', occupied='CL' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEbzBxrz6SwAWmYf8XB5Q/Ikk78FkvbBhKT6zODbCxHHSqEa0qZxaYZqaP6jHa/3TY2nQJ7Kz6n3GKqgj8PBw8Mg==', private='NO', owner='default', country='CHINA', code='CN', x='3080', y='1027', area='10000000', occupied='CN' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE85YfXA4p1mFO9jtxIVuizz9wH5R/CNW8hZ1qWkgpZhrb/EDxi+BG904PKhh2c/OwiXnePl9/Yw2GF349ZlFQaQ==', private='NO', owner='default', country='COLOMBIA', code='CO', x='1272', y='1485', area='1141000', occupied='CO' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAElfWNxy2EHbPUZoaQBO18bB0H6UjuiDWP17aUKSwKyHDi0QVke1Wj+RS3gMOBE+ecgQRBN7BSfsRz4bB8KXc4xg==', private='YES', owner='default', country='COMOROS', code='KM', x='2676', y='1647', area='1862', occupied='KM' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEt8qVCS5/eMzQkOiPHhW2vFs+Y1QCFxS1PC7mcde+I+t7MJi8EyQ7LxhI8f6nHV770rUOMhOOtSFT+ifaMLNIhQ==', private='YES', owner='default', country='DEMOCRATIC REPUBLIK OF CONGO', code='CD', x='2440', y='1550', area='2300000', occupied='CD' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAETQaDIMtMRJ6twShuZGodVo4Fg+TCOLt58Q72PAcoSY6UyfCi4hgw2dXotI4nmGfExwhxExXOgQ9lhXGwNXkN0g==', private='YES', owner='default', country='CONGO', code='CG', x='2350', y='1500', area='342000', occupied='CG' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEaHwGZnRwIfwqo2n+EJQahuxgTd9WHE4Ql25RggtPs65Wx/ObOzUCVM8yUjxDtM0j8ZKBFPhoNrkCt3lvJ0bszA==', private='YES', owner='default', country='COSTA RICA', code='CR', x='1154', y='1386', area='51000', occupied='CR' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE6r/GR3UvKBtYAm1LWrDgLFLXLII0A9K4myO51TivncuDBls72L7+ub5K6/Pa3GB3m2UrIBqmWbkGgDO+PfFCPg==', private='NO', owner='default', country='CROATIA', code='HR', x='2350', y='819', area='56000', occupied='HR' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEzbGXOMK8QbvY722585BFib7zPQE6uIYoSyM1Yq6jre3ki90u22YXTlLfux8rJxBcH/PdTkaNzFIAhUTOlP3MEA==', private='YES', owner='default', country='CUBA', code='CU', x='1028', y='1230', area='109000', occupied='CU' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEOCRy/1Uyf2wFBDxRg1yRmL1x6cS+A1aoOwbOBd8BiOLD4wKUP0SaxAG80fo+Yq+DlqpPQLKFVDP43Y09Sx4SCw==', private='YES', owner='default', country='CYPRUS', code='CY', x='2564', y='1020', area='9251', occupied='CY' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEDj9plXgtPp3kwQ7v6VZE5p9S9Fd3oC31HERsiZadejt/+2chKKGDsUHw+w1ADM7li50x8wGffOwcVOd9X2fklA==', private='NO', owner='default', country='CZECH REPUBLIC', code='CZ', x='2327', y='741', area='78000', occupied='CZ' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEqQzX2k4OFMvCSvHG7qE38qEeWjp0bvGpwvd7/x4y5iv14EHguXGLCmL2j7G1txh3oMZWczyItcEE/dqMUtSMvQ==', private='NO', owner='default', country='DENMARK', code='DK', x='2265', y='750', area='43000', occupied='DK' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEeeGlOkZaIqREGvHHM1ekKMh5oDqp43B5cIhjr/ZnV4LjaopuLPpFuR8DsuD0WWt7Krg5fc9NKQBGd3I8I8DH0w==', private='YES', owner='default', country='DJIBOUTI', code='DJ', x='2668', y='1368', area='23000', occupied='DJ' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEyKl2tKhzMbSanaGeaNA55JEm04jxdWpxTUQbAR/mCBXqKcx1AvjVJWCGRqZKzUyEqnqz6UO+URsgv22XhO6bUA==', private='YES', owner='default', country='DOMINICA', code='DM', x='1425', y='1320', area='751', occupied='DM' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEblxaVhVXi8EXp4iNqKdKtmWec4gikWaF0WSW2NXlRTqCi7IGUS0ZCYj0znecv+j3vQSazpf9zQuepDpadRfSYA==', private='YES', owner='default', country='DOMINICAN REPUBLIC', code='DO', x='1325', y='1272', area='48000', occupied='DO' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEJmSGzdwFg2eqb/mNssA6yzVULeurcyd5PNHFPMOTCeTRaBUytXsA73ZiLd+Lonsz8V4+GI7/3z7qQxqck/qp/Q==', private='YES', owner='default', country='ECUADOR', code='EC', x='1215', y='1526', area='276000', occupied='EC' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEG5GqI5x4XznGf+ELNe8bEYWdATLQ/ZdQ5//yr/A43CfAGo1eyA/6v1k8UQbzOoWD+9AqCIEFgA9byZxgww3Ukw==', private='NO', owner='default', country='EGYPT', code='EG', x='2500', y='1200', area='1000000', occupied='EG' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEDsELy+RpDQTsaHRtGRtudIQU+gDVK6EMFQuyFCp9bh6UxYxo2hq9kxIjSBc2i/48IwYv/TmF0RjILvbk9Ux6Tw==', private='YES', owner='default', country='EL SALVADOR', code='SV', x='1092', y='1341', area='21000', occupied='SV' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEUbOMb4jg2viYmjoRWVyDhnN1Qkgh2kNqlLt8IabBg/lzFcFV2saTZdfQxQxVk2tm4Mqv1WZmM4bjwWHcss3b+A==', private='YES', owner='default', country='EQUATORIAL GUINEA', code='GQ', x='2286', y='1486', area='28000', occupied='GQ' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEEHZRxYLks5V2A5BCRyWn15qTTvX3Cw2SWiwEjGIRbRbBUsygbGeE0MBjHT3XYBTWvukOS/cP4OhelDuFLYaH7w==', private='YES', owner='default', country='ERITREA', code='ER', x='2613', y='1318', area='117000', occupied='ER' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEy8xaAPhCqrlq3pLzDe6l7zYsG7KVZD+rinmUv4Vez/PvfwaATGCo4gpB8NyzqkFPv4Y/Ikt8R9kAfooV77o8WQ==', private='NO', owner='default', country='ESTONIA', code='EE', x='2457', y='570', area='45000', occupied='EE' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEWqpu5imisG3+pkrOjH2OPp1Ty/WuCxqOq1DZdbqDo4VzTAgu70M01whGCV14OFNQykLnk2/+D1xD74cgDnZp2g==', private='YES', owner='default', country='ETHIOPIA', code='ET', x='2650', y='1400', area='1100000', occupied='ET' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE0VXe2UKT9wYEt1a76dJvf3gu98edv5anYafsxeMHU5HydsiJ1r9SJxQnlp3akxi2HvabXc6QKAZOl+hEFWs/WQ==', private='YES', owner='default', country='FIJI', code='FJ', x='4287', y='1746', area='18000', occupied='FJ' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEi2wgx9d/kzd7hppaF15T4Xbo/JpP1wFDk328zahe6uYWgEqd0QwfMGQiIu/RyyhuXxd3C+JUCJQ3ZjSZn0YoOA==', private='NO', owner='default', country='FINLAND', code='FI', x='2470', y='485', area='338000', occupied='FI' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEF1MIk315tUfoXhUkuJO8q3AyOwnWrgqHu9mu5RemMJM145ALlFMKP2WA99Y8OfV/5MgdgtPMXej5LahTQnM1Sw==', private='NO', owner='default', country='FRANCE', code='FR', x='2171', y='811', area='640679', occupied='FR' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEDpK0GlYcsE6yD7IIRyYVFx+d7qrIKRf8Bf748u6nnT+fOfnvKUyqfQPM//WpslBAB59rBlcrHFShlx/ThGRxTg==', private='YES', owner='default', country='GABON', code='GA', x='2300', y='1500', area='267000', occupied='GA' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEEAuMeguGWDvHz0QTpLj/MxZjRwoDigltZqhlFG09mlBDcu9txpPXoSw2yZmsQdlfa/oPKagdVs/aN21EJypErA==', private='YES', owner='default', country='GAMBIA', code='GM', x='1949', y='1349', area='12000', occupied='GM' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAElbubzMjASBJIQi8BRfXASCtJelYjw6HEJNn7Pj2SwtYSovbbXWHXBOTmirEx8pn8E0lAMT6CYoeoaHrmN8e4kg==', private='NO', owner='default', country='GEORGIA', code='GE', x='2648', y='969', area='70000', occupied='GE' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEiU+FgDrRQhfRUMJHaJ4XiMhuKqH5hyekee17wkMh/oML1GcimUj+bd+cL4eh/s2Y1Ng97jzt4fiYdS3qNrNzEw==', private='NO', owner='default', country='GERMANY', code='DE', x='2262', y='730', area='357114', occupied='DE' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEo78DWhSv0bMQCmJW21ltqumdS/HzbXXNsqvQuWBuIn6Sr47bc7UlslqGcYYMDfg8erkrLWLc1jDawai+JmH6+Q==', private='YES', owner='default', country='GHANA', code='GH', x='2148', y='1412', area='238000', occupied='GH' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEDwbc+2miqMJ72weeHL5WigQe/cBMTV0ukTS+s7mfh5hjLK9DAWy5I975ryVhQxedhiL1arUAO/NWxEN0lj+lDQ==', private='YES', owner='default', country='GIBRALTAR', code='GI', x='2096', y='1062', area='6', occupied='GI' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEx6GelT4j13I56Of1ZNfwH5WmvEVXCsAZy5wctILTncgCFXXhL3TgpijA7igqO7TpN/Y+KdhTFBiWoBzrqS9GEQ==', private='NO', owner='default', country='GREECE', code='GR', x='2418', y='937', area='131000', occupied='GR' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAERuHR3Lzm8Zq/PrvcMutDfDTSrD1sxPigrFJl1eRpfvEm+UBCxSouL6NvANwBtkc+lOb2gnapNnDisdDHX+7Ljg==', private='YES', owner='default', country='GRENADA', code='GD', x='1422', y='1361', area='344', occupied='GD' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEWH+b7tdvY0e/Oomcfg+Xy8atRus18vjOe9U87ZwV9vmtbTJKIq+w8mLi4Pej0PDk+/hfww0OcLW2PbcmYuevKw==', private='YES', owner='default', country='GUATEMALA', code='GT', x='1080', y='1320', area='108000', occupied='GT' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEqGMNf1PBeIHix0BTy817PPHIgtSP9Pdwv4a5J9+E3uOEhgMtPxKUuLbn4hXQm2YxPzC+KK6Ch3KpNPBcM7DRpA==', private='YES', owner='default', country='GUINEA', code='GN', x='2037', y='1376', area='245000', occupied='GN' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEM3kLqd34aBdavHcXYmveSehZL91RjAClA8s+njErjZGlTk7SgoY+p+pvGyfRcO6coet92+ZvmwRCgRHxV5n9ZQ==', private='YES', owner='default', country='GUINEA-BISSAU', code='GW', x='1980', y='1368', area='36000', occupied='GW' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEMvphM5aynElM1DBJTv/rYA2CpJvI772Ur9Jk8bay6WKcNXo92KnYx50z+b3IwwNGiCbS00DnFB+dFbuha9tq8A==', private='YES', owner='default', country='GUYANA', code='GY', x='1448', y='1439', area='215000', occupied='GY' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAECS0mTp9nX5T8v71ot0m4KMUUw7MLjoNJAnP4dTThQZ/4D00xezcbUT0V9yeUvex198jKC0nF7XbXS65OTb5iRw==', private='YES', owner='default', country='HAITI', code='HT', x='1300', y='1271', area='27750', occupied='HT' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE+3xpXrL0HPrCgg2e4uzF64JQ2Bs+zmSb0Djy2KCzlvwmWklJfHl4LyIhkf0f1LA/nTFBrJNlT4ij6Z4772P4Hw==', private='YES', owner='default', country='HONDURAS', code='HN', x='1148', y='1323', area='112000', occupied='HN' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEvyrAUs8hYqixoJECeAcZbgc6k7TFCkfiyZG8RELMoHHeG9tHkbeDq1dIOnnxeTXj3vvaP/xZmjvuQmKjwsr7MA==', private='YES', owner='default', country='HUNGARY', code='HU', x='2389', y='798', area='93000', occupied='HU' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEhYoAdFStQg8S/zun/lUPbzU4pLUjgbshWJl2zyEBjG4o9/o7utQNAR9mHdc4Gu8VOsPg8XnX3kORxVh6QRtVCg==', private='YES', owner='default', country='ICELAND', code='IS', x='1976', y='586', area='103000', occupied='IS' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEOSyOFcnpGNuLNA4WPzXiBF+H6QODImpwb0hexVg3LN7+wZ6DArLKjeFLA7PExhkHeB2hDzyaJy7CMqD9DEEYow==', private='NO', owner='default', country='INDIA', code='IN', x='3086', y='1229', area='3200000', occupied='IN' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE8MoNbsRi+O/CgHYK0XW9L2t+9p3hNEkED5YFa7iIBUVwildfQMGdDc8gLASfjkgOVzwM+XI3/hiJabsZM4ESLw==', private='NO', owner='default', country='INDONESIA', code='ID', x='3531', y='1517', area='1900000', occupied='ID' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEHQS/m2L1iiIlCweygUZNP81/KKjH30XCcVjqM1xYUbnp6eF59+iOfvjMUhTsyjL1lKkMQj+vfpPVnej82r4taA==', private='YES', owner='default', country='IRAN', code='IR', x='2800', y='1100', area='1700000', occupied='IR' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE8vR4yRcCOpiV4K+cUlO9d2dWcpXrO+77VbESGkVwhrgmK4gVzuHMOXjwgpIXyOqF+U8I1R6hJdIvQhQZ9yOLyw==', private='YES', owner='default', country='IRAQ', code='IQ', x='2660', y='1100', area='438000', occupied='IQ' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEKIq65IBqO8LzLZfpD7n6k9H6ES0OOGOjmbLcOCLNvUMTkLcb6VzXTlC/BwbdYnZvI3TUH0ks5GrRDbNieL4C7w==', private='NO', owner='default', country='IRELAND', code='IE', x='2258', y='750', area='70000', occupied='IE' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE+gx/zit/IGJyw31NGErZ7pUFyUBlE5LAsLdoJ12wtnu7/c+1CxUyJNth4N5WgnEXZgVM7GnoAdXT96KBE+Au6w==', private='YES', owner='default', country='ISRAEL', code='IL', x='2566', y='1117', area='21000', occupied='IL' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEhKhg9k1IgWGDxed6kK456riDaCMXlGI5u1lLDmo6MJB6FEec1L8QDCxk6AulUhHbXM3JGv5HhbbBa9oWVIcDcg==', private='NO', owner='default', country='ITALY', code='IT', x='2280', y='838', area='301000', occupied='IT' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAENcyITRu3UxSnuZJYtHLH21J9iFdiJFU/hKv3IGthkxdb4mf8ilU0Qv/3TWotZuF0jAIdlDTywgU+7f5qH3hvsw==', private='YES', owner='default', country='JAMAICA', code='JM', x='1244', y='1288', area='11000', occupied='JM' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE8JpSesBPojuvAw1xHbge3E4olDBvZtIyHA4m9B3SEuGmzM1Mm82H5R4oUq6pA5qQZ8I1NVN/WTGc0Cq4RPh1KQ==', private='NO', owner='default', country='JAPAN', code='JP', x='3777', y='1000', area='377000', occupied='JP' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEka99njSp8Mt458+RVFcVDpew1apAvP+y5I1cr4f5AyKMJal6p/CB5ZjNmWsKmnfcmY4Od0ncfXW5oJBv0EJUIA==', private='YES', owner='default', country='JORDAN', code='JO', x='2580', y='1121', area='90000', occupied='JO' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEcUlrQxRj6xJv/ltmwN+/ct9vqWKmCeOIDDrQ8tL+qjBa+XOkUQKR40LXdMj3bDRQT2Zhn0Hg7IMvQ7lv2AwAxw==', private='NO', owner='default', country='KAZAKHSTAN', code='KZ', x='2900', y='850', area='2700000', occupied='KZ' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEtTaaocK45tWGKBtRv+lVwN2cZoFf+OxMCECDp4/omzHiEVGClyzl8rvLFnCPe/zyTR1QuI1gdx/eolCtzmCUAg==', private='YES', owner='default', country='KENYA', code='KE', x='2614', y='1500', area='580000', occupied='KE' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEvr6Re5VIJCtnFmIxL9P9KUVx5TFkME2q29sIsoTzMahOiRDrd55/QHvWoc0J6OSWMbXTgky2IgLw8Kw4WakzNA==', private='YES', owner='default', country='KIRIBATI', code='KI', x='4278', y='1519', area='811', occupied='KI' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE7h/HVl+4GwPVaXcE7Oj7xVF+gccqbs2PH4kyF79OgyDUg1bbaYf5yn1tNjAmAFIQW/qyMJLu6qgtFYudpeQScA==', private='NO', owner='default', country='SOUTH KOREA', code='KR', x='3645', y='1006', area='100000', occupied='KR' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEp5DxPBVc4vvxmCbN2pZ/Bs07qrhpbzVrBMSZ+NV+wK37btTVE2r7jJ3yWz79pVzc90W2E7j6OvC1mhTsepgvjw==', private='YES', owner='default', country='KUWAIT', code='KW', x='2714', y='1144', area='18000', occupied='KW' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEghBS2SIPlRJTMw4JpCsREW4cYr5DL+xHtodev/950il7vlRErHUohrtnwZz+Q7uM36MwdSAyYAOmiudzgvuvWA==', private='YES', owner='default', country='KYRGYZSTAN', code='KG', x='3000', y='964', area='200000', occupied='KG' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE8PDazc1K8nkt/aJTNmd/aSSWsUvcpOt60DKSl4vQxnHnHFZCC21ByjUGlrhDDxsmLKry7ueBsZLTKGq2ICiA4w==', private='YES', owner='default', country='LAOS', code='LA', x='3377', y='1255', area='235000', occupied='LA' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEVCYNE8YKjnw88Q0T4WCoPeWDtC50AbfThLfOYyWYdUI+RssxeAQUnArQumm0kVaY/mgVYR44ADcOsZWf7mhO9Q==', private='NO', owner='default', country='LATVIA', code='LV', x='2465', y='614', area='64000', occupied='LV' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEs1Tw0wdjFzUHAmZ0xBIDRenWLzLD+2PdcJR9tzax/LRbHdDD/7IUxeynwYaKLEndO83MYn6WPeCBqXJCkBN4LQ==', private='YES', owner='default', country='LEBANON', code='LB', x='2577', y='1082', area='10000', occupied='LB' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEUSb3mijUDMj1KPSiM29b7VR+f4ncyNyPNwHv95L6ye4EsVVmTdVOuESfcfTpfw5XK3zciwQ5W8OnKAQlN6h+7w==', private='YES', owner='default', country='LESOTHO', code='LS', x='2490', y='1873', area='30000', occupied='LS' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE9SZXTpu4fqyKio+U0lm1Rxo9ww2f1fry4u01D/2Eldqc7u5z2abjgGk3Y+OUkyVKVHfGTjbUwBZo2Z29UjD4Ww==', private='YES', owner='default', country='LIBERIA', code='LR', x='2038', y='1428', area='111000', occupied='LR' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE0tpqEk7ZC5QKtbokfX/iX8T52ywolI8zfRzEXGySdBu9uarGLBi0Wy7sRogS4xE4So8LTf76MzO2uFn+8WaFVA==', private='YES', owner='default', country='LIBYA', code='LY', x='2358', y='1176', area='1760000', occupied='LY' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEwJAG24fjJ1qjlA7kgbzJopmFDxg6Pn6oRBABX0qPm2POLbLcb9+gNuF0dCkesdgzti4oRlkgS6N/pEjhJSghvw==', private='YES', owner='default', country='LIECHTENSTEIN', code='LI', x='2286', y='900', area='160', occupied='LI' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEXWB3BCkppeMZOJCl5VkX3of1yGcqK4c48FzX5pVMYVdXvVoUia3WMC2rgvWbYQNuxKZOrJRKBYkmW+KbySus4A==', private='NO', owner='default', country='LITHUANIA', code='LT', x='2447', y='654', area='65000', occupied='LT' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAETclT1O3kS6y2fIDcUwY0YyHQWkrPaHEArUIiQFdVgR/EBcWVrxOuhHILyiTXw5Q7fkNO74BnW5oI8vonzHCXVA==', private='YES', owner='default', country='LUXEMBOURG', code='LU', x='2210', y='741', area='2586', occupied='LU' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE8KpMS9kbi7/YQzkRnnR5+87CyYvhbDlWdB3Av5nK/GcEN6m7kFkId0NJWEEaFWmoZUJatzfMIVRlEN2J8w35HQ==', private='YES', owner='default', country='REPUBLIC OF MACEDONIA', code='MK', x='2331', y='811', area='25000', occupied='MK' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEmlew3xWXbIeB96NPwEfZSGPHUkF7Z25O4oX2C1Em2g8Gw9v8JIjdicj4WGeS4z/ww4Wxp+zERVTKCHdWP7Fygw==', private='YES', owner='default', country='MADAGASCAR', code='MG', x='2710', y='1744', area='587000', occupied='MG' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAESkYRMsrrsjVXmrf1B7JLb4Pk02pQqC7IWMk5lySso4lxAn0HECeNbBX1J42TuVqWwHih0V6tNcwk/xJkCEspfA==', private='YES', owner='default', country='MALAWI', code='MW', x='2564', y='1677', area='118000', occupied='MW' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEQz75M0myYJgCM4N4oaxMeTdwv98KKPTeswcEOah6GfORXgpKQ9bBo6hchEFRaFc0nTNJrwzDBI564LKG7xNATA==', private='NO', owner='default', country='MALAYSIA', code='MY', x='3385', y='1454', area='330000', occupied='MY' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEhDbV8qB0Xm40QuydIULrQf1IaTwegnYfvC5Gu8JOREUAmuiRjpWvbgAKsw0BqWeVTvuxZpNvgmVoa3eY1y2rAg==', private='YES', owner='default', country='MALDIVES', code='MV', x='3040', y='1453', area='300', occupied='MV' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEKnemjZpIizcZ2yduBqDZtM+dOqpCK98uR4Ju0A8RC1xRe50myAI8l8knYcVo/N8R/tTOwW+PbBAKfyYPv5opHw==', private='YES', owner='default', country='MALI', code='ML', x='2150', y='1300', area='1240000', occupied='ML' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE0cbCU0TYQZswJXTU7zzegsnWM5K9veJrGdBurnYEgx53r7j//7vxJ37RV2JSoavQvmpta8150qs6Z35TclZukg==', private='YES', owner='default', country='MALTA', code='MT', x='2327', y='1005', area='316', occupied='MT' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEQP9rG1RcxsrM5Ft6Cwm8wIfP1ucYtVDORLNJVhhM+Xq9UcnFiV4to3QvfQUhnP0tD5xOkFBcs/As6pstgSjTyw==', private='YES', owner='default', country='MARSHALL ISLANDS', code='MH', x='4178', y='1358', area='180', occupied='MH' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE26dU0ZHyA86hYmVEzbSv4ArqtD0+MAKTaqETL1f8HSYroJVPnC7B4pRVmJ84Zb+FloB1vOses7gun6KJwVibqg==', private='YES', owner='default', country='MAURITANIA', code='MR', x='2000', y='1300', area='1000000', occupied='MR' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEfuXemFGN+C4SD/cyg4+sKQukX3DPeW2M6fF/lEv8NTYkO0hdqgiFP1iRxdq7aro5TxZSbs8CdbDy3KqlA0JUAQ==', private='YES', owner='default', country='MAURITIUS', code='MU', x='2846', y='1754', area='2000', occupied='MU' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAESOkyP+QcSM5Y0OZZBF4PLNb1oczT0jHMEJ39j22OF34QhCEArsZu/HzUUiiw2mfbZoIUMpH063LVKUI7/cI1wA==', private='NO', owner='default', country='MEXICO', code='MX', x='940', y='1200', area='1950000', occupied='MX' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEW1DHyikE8TxYBrKklhnmpNrcF9cOb1dOwpKiIQVH2Xf887Lv+Mjfxo0PEYW/NlxLU8xyj9juKi8jl1V0NwLryQ==', private='YES', owner='default', country='MICRONESIA', code='FM', x='3968', y='1434', area='702', occupied='FM' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAExHxgrFJmxdGGVwj/KTEydHh/AVM84gRPIN5lbtO3RF05saZaESUuNX5OGw5aTw2MmQXtw5xyPAObZ6RDGcZIoQ==', private='NO', owner='default', country='MOLDOVA', code='MD', x='2503', y='792', area='33000', occupied='MD' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAENESxq+SFa2dX0PTUDgo+xKUelfvs7T7He5OVXoJQ8XGJV7NdS9lh5YhXczG8sZG+hwRGpuy/JjqA8oZ7uxPI/g==', private='YES', owner='default', country='MONACO', code='MC', x='2246', y='947', area='2', occupied='MC' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEE/6B2cCfhbTkIh5B33znc6vJRXk2SAWIYCBEXGv3wHaW/JGsbD3LmzqPZj/Jwxt4Yk3EPhgg0cP3ceuvB7U5aA==', private='YES', owner='default', country='MONGOLIA', code='MN', x='3333', y='857', area='1560000', occupied='MN' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEtzjZFKmpdbFUd7LSVhGUDw9cXTK9Q/jbW0fqjgspWF9ox5IgMsN5gx4og4c/O8dTyt3kmt5zGNrEy0rtjeKgVQ==', private='YES', owner='default', country='MOROCCO', code='MA', x='2100', y='1100', area='446000', occupied='MA' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE0AW9IIVBKHB+oX9/NjpwL9CbqahqjYfz/s0GfxKdkOc3OKObvTUZ4t4MK5RtLwkZ6RkAXv0mL7WDL1uj5tCaJw==', private='YES', owner='default', country='MOZAMBIQUE', code='MZ', x='2610', y='1680', area='801000', occupied='MZ' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEEITSjNAPDRJjUDAVRxiiLXuzF6Kr8LluQMNJUOsVxz6mEtrgBUJ236WENJe19bL57IdDajfbVBb+EVkzjUKkMw==', private='YES', owner='default', country='MYANMAR', code='MM', x='1232', y='1125', area='676000', occupied='MM' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEsc7DCAuvslzURCHUINRmppK1E22HUnINbXoZvywfZTMUGF5HjQ4IElcLdq3IIwpV/ECc6l9Ntnw9og5LVuRmpQ==', private='YES', owner='default', country='NAMIBIA', code='NA', x='2360', y='1770', area='825000', occupied='NA' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE9/LkTZTG97/9QsGJCPEni3O5Lo5j9KbgZerKLUYLVdikQvTT/kteoObEeXKSNYE8ciyYNWtot6QKwqU8lGzREg==', private='YES', owner='default', country='NAURU', code='NR', x='4166', y='1512', area='21', occupied='NR' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEihhzSXX0BqO/hIJiHqAIRFz1dohGytn44iTbkDmQqhs+5uWyPsZmX2p2HcVVy4AjxlDFptr+6/YkCBtR8mrOew==', private='YES', owner='default', country='NEPAL', code='NP', x='3136', y='1145', area='147000', occupied='NP' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEL3FYfnN/thk5EpEBDtHLgeGr19ipauhtpbZ5yd34Yuz7LgFpZBTPP4JkZ7WynIeLSHLAHcpShBv9yefC7Y5idQ==', private='NO', owner='default', country='NETHERLANDS', code='NL', x='2210', y='703', area='41850', occupied='NL' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEJVcCxAE0gi1QdeINZef6nJMURmFbTqBFEZ5DaCzplewENbwLCF+pvo60E4bkbROwinoRnhwJcJv8JgMSIgmCRg==', private='YES', owner='default', country='NEW ZEALAND', code='NZ', x='4126', y='2200', area='270000', occupied='NZ' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEXsI1S7EfHMfeuUK/ErzXEA32NSiXblelcSzegBJ1OmM6ycPJdfAXX1R7I1FXWadHEF6z3DDseUnJo4x7KMxKFQ==', private='YES', owner='default', country='NICARAGUA', code='NI', x='1149', y='1350', area='130000', occupied='NI' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEHFi6i5Bx1aRZR49eaeK4lTJBEz6tgzpWCGmumcvZbKh4ERlBJgmhJS/C1h1F+WIsOS8C7uBtZfI6cwJEiqapaw==', private='YES', owner='default', country='NIGER', code='NE', x='2300', y='1300', area='1250000', occupied='NE' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEcvWyBKem/jcegYhpRGtb+6yBR1F8XJ72j6uduZ4JI7L69lsxQM2/zRBaIiz3RabA5DyJopI5syX65UzYi5Tqrw==', private='YES', owner='default', country='NIGERIA', code='NG', x='2250', y='1400', area='923000', occupied='NG' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEnmvqN8auc/2PR3hOc9LvyUtvRz4Yojk/Vswj1bXS7/x7jF7U6R4Bnsk0mBY5bKKYJttzwN+nmArvmdubra8HIA==', private='NO', owner='default', country='NORWAY', code='NO', x='2265', y='534', area='323000', occupied='NO' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEECAhLB8zY+H57sz9ujZ9H9nzqqnmNqxg40+VDySO3ItV1iD/RIySGU+UvIfce/jtZDdCGqTar1rLHam/ALmvsg==', private='YES', owner='default', country='OMAN', code='OM', x='2827', y='1250', area='309000', occupied='OM' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEXQe/JOkvylnoBBel0sDRmZ8Hw29ZYgHbekeVKYC/zztzB1JPZ8KYWlqzXcbnRbGVhF9GVAkq9nxWLLdiw6nNCQ==', private='NO', owner='default', country='PAKISTAN', code='PK', x='2962', y='1137', area='881000', occupied='PK' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEnWw0JCfbROP+YwSjpz4wd7T86U0DOl0R+UcfbG+GKbgLkQfbX4xEkXA5OK0n50UOvKAA29VJ+LgJ8O6SemSTpw==', private='YES', owner='default', country='PALAU', code='PW', x='3771', y='1445', area='459', occupied='PW' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEXAwdcWipvQQv/py69UH2En2uEsIOdWrWFcgIx5sVC/I3EJCsOgmx1stN0GvrGMNGPqx7XMX2PL9PSPR3YxcKwA==', private='YES', owner='default', country='PALESTINIAN TERRITORY', code='PS', x='2559', y='1116', area='6000', occupied='PS' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEjsxrq3jeKck1M3naqrSh/G7GrHHjXm4MlKYYR1n61bG0qPDVWmHTsvnAHcjSnCiwyvZmOEooTgPdKzLkRdOvSQ==', private='YES', owner='default', country='PANAMA', code='PA', x='1187', y='1408', area='75000', occupied='PA' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE/vc+We4PtmDNTsW9+4YSy0l+9OeZN0Gr1Z04q9QG6B9LNAY91l/YTNWsmZMoCA2ijuPvTYreEByvOclUQlEKsw==', private='YES', owner='default', country='PAPUA NEW GUINEA', code='PG', x='3884', y='1583', area='462000', occupied='PG' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEPyle3yxjAjvhOtA/hBBKV+5Wzs7am/3Rwcup7AxJ7C3Uht0SYqk1wAFKHhFlzBjxoUNY8KOwWkkQZ11kTcenlA==', private='YES', owner='default', country='PARAGUAY', code='PY', x='1448', y='1776', area='405000', occupied='PY' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEeVO8nzS/fj4z5CDKv188rKRLnS7bNg34mYCwCs07fRX0G5z9S/u4jvKFcgm0ZgKIg47iW1h3Sbtuyu/qhGGSag==', private='YES', owner='default', country='PERU', code='PE', x='1255', y='1573', area='1285000', occupied='PE' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAExz2zJNP6alL4aCxg0oyIntfypdqK8u+vilc8fMj1MlEtv6HSYQwACupcaWuD7G0m1v6zGHoGqCvUKilyQegSzQ==', private='NO', owner='default', country='PHILIPPINES', code='PH', x='3605', y='1329', area='343000', occupied='PH' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAExGxh1dBTj+tjN9rT6n5aeToBmA41FeC+LM636O0J7VG5WMfNcrHU8d6QznjW9uM3HMHskljxXgR03rfBeQPNzw==', private='NO', owner='default', country='POLAND', code='PL', x='2389', y='703', area='312000', occupied='PL' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE53e+8L9epREc/71jO2ZCl89EkAjJDziqwv3uF6ODV0Zdv9M6wIihRYCl9QM/IjG+wJW8y6TYhyUi1fvftEFMLw==', private='NO', owner='default', country='PORTUGAL', code='PT', x='2041', y='931', area='92000', occupied='PT' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAER/cHt2chCtaiQ3mFLx9l2e7nzjhAlD5+l/YYaJzPmBeKlPdhIFItWXEsPXx7x3I6wnTpj8XGoXg8j8kARUdytw==', private='YES', owner='default', country='PUERTO RICO', code='PR', x='1362', y='1280', area='9100', occupied='PR' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEIf49h7Ls6aZVrIo/BjSXlmzc+pM56UT6LcaOousJiTOGe7Q9JLuGyXHT70i4LtrJCJ1RgRVD2JaaWTVWKLku5A==', private='YES', owner='default', country='QATAR', code='QA', x='2761', y='1197', area='11500', occupied='QA' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEfrOZfF/uuSIt/xIvpmXH3a0A++nXrS4Mw1pIpwwYI/9PRHiXTX0LDGx4IY9lf6oHcQpZLMZq9eFfciOoPW1dDQ==', private='NO', owner='default', country='ROMANIA', code='RO', x='2457', y='817', area='238000', occupied='RO' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEouR36rqcYyt1nCgsjglIf3RICstkU3UoE4fD3X4vX+nLYS40PVkwmjpwQkpUfrKwbkDT+sUR555oTOC2o8Pn2Q==', private='NO', owner='default', country='RUSSIA', code='RU', x='3380', y='513', area='17000000', occupied='RU' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEh+O2elM5AQDStf5Hmu6McAI1a0LW4xRCOqiDz/vDCrUmWbgalESzqglIgVOPW7d9M60nnt9c5aWSjMlVChp69A==', private='YES', owner='default', country='RWANDA', code='RW', x='2522', y='1528', area='26000', occupied='RW' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE/HhXSG5gVS/77b7LfN8GAuIvxybAV2aeYv20eb12EG8P/jrLYbHfl01+ZV65JebthPt+m46Q1gm3BpRCdkxZFA==', private='YES', owner='default', country='SAINT KITTS AND NEVIS', code='KN', x='1417', y='1298', area='250', occupied='KN' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEVI45Lre4Fb09KK03/HN/N1DnZdjPX1HadA/KuFPRGBT6dqfzefnUJ08uovgKw/oqAnsPu3FtNCCnMSHEDC0ASg==', private='YES', owner='default', country='SAINT LUCIA', code='LC', x='1434', y='1339', area='1220000', occupied='LC' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEve05Fc2pQYTRibmhnHdWci8Y/1sstCijwdZCZeIuOaXdXSw9xbaufBToRyzqgyIm/VGJq58wALVMNq2igwpc8A==', private='YES', owner='default', country='SAINT PIERRE AND MIQUELON', code='PM', x='1537', y='898', area='240', occupied='PM' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE4EKqnB2MXMKTUUSMS1juxGI75YmyIt/6lV2BU9j01exEmwsxZCnFOhfO/NCKqmGlC6v/xXmbT7GDd7Qw/6hfXw==', private='YES', owner='default', country='SAINT VINCENT AND THE GRENADIN', code='VC', x='1420', y='1360', area='389', occupied='VC' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEJLPD2QGA18xSaPJ0L8MRbwVjo65PRWoU0cVOhLFFBvt8MfgHNY1lCUnvadUDqOBiqQOv5lKKPnJ1A5iEs2Ntew==', private='YES', owner='default', country='SAMOA', code='WS', x='4313', y='1395', area='2800', occupied='WS' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEmqR2MhpyDs/+84aJi89DvBlLKutYT+l65Pq+OFf5kmQAt6ovnO0QtkBQZpDQY9I1aT0s48nuG1b64/ug1WYztw==', private='YES', owner='default', country='SAN MARINO', code='SM', x='2300', y='946', area='61', occupied='SM' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAELGkrFDSE+ONqbIJ4+c0/KQimV7kQqQRNe5hf6OSMraT7fiymnH/s/Qrzc2/4wIg/ye4c/FpL3jEuIE5tw8oykA==', private='YES', owner='default', country='SAO TOME AND PRINCIPE', code='ST', x='2237', y='1524', area='964', occupied='ST' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEKUu1uuu/yN/zIb86lIsWX2KByM4Xa9b9RNjWG4WPXcgIiEHgTjFGMGwIrYTGbAIXzT4TUdDeKGvE4eDbcBgj7g==', private='YES', owner='default', country='SAUDI ARABIA', code='SA', x='2700', y='1200', area='2150000', occupied='SA' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE1fYXqOKE+HMk7N1Db9qPzhfI1ZqSJqRuidX5O8RGQm/u2pTqxmrp7CT2wTF8NebmD830YhZnZ3Y4GAf3zqqLGA==', private='YES', owner='default', country='SENEGAL', code='SN', x='2000', y='1320', area='197000', occupied='SN' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEBViOu8QdptMOIsTJWMXMmCcduRLsSka3rY/XDWcdnWTzvNFXh8o5chG8WG8sRkFF4ZTdjme+bskK5g8sjLqPCQ==', private='NO', owner='default', country='SERBIA', code='RS', x='2405', y='851', area='88000', occupied='RS' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE+0rZmEZbPAKi/XRDkuTBeWcXZsWuKmuxWkSR9Xpm5KQp58ElIpUW+/YvHj21JJpgUDdp8I8qxQvM3K7nPXX1XA==', private='YES', owner='default', country='SEYCHELLES', code='SC', x='2769', y='1616', area='450', occupied='SC' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEXOVylreDY/NUlLu8ujRe64/M9vPAJZJrcxtzeejV1tomo8TTdOgF+t3B2bJ4c4UPODCioMOQ6F1gmMAJpWFYtQ==', private='YES', owner='default', country='SIERRA LEONE', code='SL', x='2020', y='1400', area='71000', occupied='SL' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE3+HTbVdwRNRwiBCUJ9MLr0kGKhDWw+RuX4HdvTvVZznVICrGJ9b3YlB4mta0QbVlW59lS6fHbluhvOziIQ4D+A==', private='NO', owner='default', country='SINGAPORE', code='SG', x='3408', y='1496', area='720', occupied='SG' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEiCb9hnlKMloM7NrPioGCwDhb6NHbGJmEsl+KB7XFpjb9uvNY4Z0BOIJ2EdY3gOK0ufjD8B0ZivomT7Iaud9vPA==', private='NO', owner='default', country='SLOVAKIA', code='SK', x='2391', y='766', area='49000', occupied='SK' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEdOGNk5J8jT/66TNIPvCr3E0oz4mWGk+6SqZBFhYYsQQFrZ09o8dbVCXO7939wtNZKm4zGmRM56Rrc7yUJvwb9A==', private='NO', owner='default', country='SLOVENIA', code='SI', x='2335', y='813', area='20000', occupied='SI' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEvhDkK2Ydiaoewu4vE+HKx0iH/LgTSMNHqFUaOQ3JbXAJ/Nma9Hg3RD1AerZRwhelF+L4tCm3/bix6bRYCzwc+A==', private='YES', owner='default', country='SOLOMON ISLANDS', code='SB', x='4146', y='1626', area='28000', occupied='SB' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEh9NtC8So1dxgcv3rdqP8+L+7As1EBPdMkqSvj8Hu7q+PEXEiF8rNSoV3skoXWpAXoSMIWR4nrh7O5Ztv/FMdjw==', private='YES', owner='default', country='SOMALIA', code='SO', x='2750', y='1390', area='640000', occupied='SO' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEV7nCo5iF3sOJL6J9IudOspho9XnxsVCw7XHzKwzQ6Wm65gB5YkycI1TL8Y4X5rxxeOSNjntNWdHnx+v4XRAYxQ==', private='YES', owner='default', country='SOUTH AFRICA', code='ZA', x='2428', y='1883', area='1220000', occupied='ZA' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEypUGQJc2NG70EmrYtZJLHj1ivHyauADgvSvZbTaregiwmiuScEPBQAJ11Ekr6exDDFUi7AuUWZ+oShSBLPDsuA==', private='NO', owner='default', country='SPAIN', code='ES', x='2080', y='912', area='505000', occupied='ES' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEoHvQYmQXQPBo1NuDW0At6G4y4LeqFDT7zR132gluibBv/7tEd8i6SVan1ffvdHjAZlruhCL1y7TRe4tLjINHEw==', private='YES', owner='default', country='SRI LANKA', code='LK', x='3125', y='1416', area='65000', occupied='LK' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEQS+i6OM8ZEbDt5MKETxZE9OWag/mXSeu22oJysTYMIG8rJyVVnLUdPyx3rwR0WWx6dS7Ji9UTUUn/4wXA8oPWw==', private='YES', owner='default', country='SUDAN', code='SD', x='2500', y='1300', area='1861000', occupied='SD' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEcTBscX8XLWSw56uoJnyrZSmOCky3ADcDKCHmTkrHkRvoVVpQ8RisAc80GLMwnloUrGR4JchCzCBqotZcCwsk5w==', private='YES', owner='default', country='SURINAME', code='SR', x='1488', y='1487', area='168000', occupied='SR' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEmAoChknOiLezkCifYHxk3W7/8kjAU5ewDnE37DZmi2aAnWVGiVIviWHZFpg8tMQmwRosPAgcEYV+D2qA7O3Maw==', private='YES', owner='default', country='SWAZILAND', code='SZ', x='2533', y='1836', area='17600', occupied='SZ' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEEAwviUsF5PK93+Cpr5YbHks8ga3w3c0/VTQiaoSaK0QJd4DktJF70TfuJvd39Ii9k+d0GjnL31F857iTuJJGEQ==', private='NO', owner='default', country='SWEDEN', code='SE', x='2327', y='551', area='450000', occupied='SE' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEqsChQEwiQ6t+IQ3wjiaRjmi+llX3UfGx+xKHnoyKSIaRVIE2OB3A8+0BwIlA71sWolOYPanxCQBKdVb1ogAGeQ==', private='NO', owner='default', country='SWITZERLAND', code='CH', x='2249', y='798', area='41000', occupied='CH' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEZaYnJIMYM56gnZzm2fIMPnHrd3Oqpxc8yCJM0lKQjbZAvbQlV9Xw/3aitZo1ViEvRQPzvQsDF8fVqg9sCJoqDQ==', private='YES', owner='default', country='SYRIA', code='SY', x='2600', y='1070', area='185000', occupied='SY' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEFOu9SqekICFoQUldIyi7mbzlz7V5F2d2EK0d7twwH/Q4RGqikh2zB9922OKRnN9tWR9SHfaa41E+AafS9/F7cQ==', private='YES', owner='default', country='TAIWAN', code='TW', x='3596', y='1198', area='36000', occupied='TW' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEMobBOUqnd+d9iU9xPehVcgLaFWbPvngk3u7wd3geMDPLg0fAYiJPUE/UJOcBm4xZgtPJQpYh4sH/x0WS+ZJ+ow==', private='YES', owner='default', country='TAJIKISTAN', code='TJ', x='2956', y='1004', area='143000', occupied='TJ' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE3sEhP2C5T40c4t7azaNT3//N1WW8JTI/iAJtCoHh6tRJJofydER/soGTWNhaIwmvTuYN6YmypqN4ad9JqCQJuw==', private='YES', owner='default', country='TANZANIA', code='TZ', x='2588', y='1575', area='950000', occupied='TZ' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE+NfWlZvnv1rHl+slmILOnPtmf+FjzmDpnluozTy7/Apnq0XaPaJOwd6c9NbEuCKIbBX42WN6cyxxvpsJZAu8gQ==', private='NO', owner='default', country='THAILAND', code='TH', x='3372', y='1308', area='510000', occupied='TH' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE3I4a8rAQZLbOAZ5G0lbavPc6GTGr5zXRa4qSWGE3LYpfcDAOz6S/ETDP8e2UXe2WhB1GloCs1g3YvfAX4Y8Odw==', private='YES', owner='default', country='TIMOR-LESTE', code='TL', x='3670', y='1617', area='15000', occupied='TL' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE2b0LHZ/BzwrDOMxUfDd7Bu+a4pzk88jy5Kt7uCKtRcLmp909fNRQUsNrM6ri0g/8rrQJJwd0bH6QwJqRW1035g==', private='YES', owner='default', country='TOGO', code='TG', x='2174', y='1410', area='56000', occupied='TG' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAERk5K0J/JubkFZDuCZdboRSS2ld54znPN/91MlC0MbmT8LWPowtH92TL4ajKrDLSJqwIfiRm1aiU5Qw5vKBHE2w==', private='YES', owner='default', country='TONGA', code='TO', x='4313', y='1777', area='747', occupied='TO' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEvwP6ZAkkAdPVsW5yEAhLkJnAoWXOKvUocQEaKmaEuiXWM/aXT978y0+UvJVuljCSvJxFGJhcF78eF4s5vnNVnQ==', private='YES', owner='default', country='TRINIDAD AND TOBAGO', code='TT', x='1424', y='1380', area='5000', occupied='TT' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEsYfx1J8cUNDe/FP1SJ6y3NneocKv9bdR4qeCFwLlYLMw1qEQSZK3LQxj0v0j0PbJw1fQxWh5D8g5YZCJ+zchxQ==', private='YES', owner='default', country='TUNISIA', code='TN', x='2200', y='1100', area='163000', occupied='TN' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAES26oWmcmBUPjiUM8ocv+lcnADdfOTkFugscImTIFqYrMOlio1EetmSHwAjG73qBJlM7sCFtu9f9SkX8ruDNKNw==', private='YES', owner='default', country='TURKEY', code='TR', x='2600', y='1010', area='783000', occupied='TR' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAErOkad+u5QzGjY5Ul2Rxv+QRtEORVfjQ77kHvO7hnGAUsEjU8SPD7FHfKduwWvepYOtB7e9xW+Qrdo1AQnaSuUg==', private='YES', owner='default', country='TURKMENISTAN', code='TM', x='2800', y='990', area='480000', occupied='TM' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE4SyZYn0hzw4EnLWZyOUTMAae1hb5u5zy1NxEw2MR3nmHs5p0gcSjDoCs6ByFARGNzFwvjdjR27Uc9Sc5c78CbQ==', private='YES', owner='default', country='TUVALU', code='TV', x='4288', y='1590', area='26', occupied='TV' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE81pVA7WZ+R3bEZPTSlzzUycOQs60KZC8Dw2AmxWabgSK63d2oZCkPCGli9Iiqcl0otGwDoQkPdlzhooUpg/NFQ==', private='YES', owner='default', country='UGANDA', code='UG', x='2550', y='1488', area='241000', occupied='UG' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEKm59RSxZNViPHV2ly1HFo4ta8IZ4HgER/2DDaLwu0O6yWwiMrqvkY/JnIOXi53iBnwm3B7aFmCkK/X7afM/f5w==', private='NO', owner='default', country='UKRAINE', code='UA', x='2535', y='760', area='600000', occupied='UA' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEFQFBn0ypBT9RPLqknkcnzw9yLCy+ZxXSmIRTXMpytzYO67P+SnGiEaH9mHAApBDEvMMEmstCXFKOqC+b78VNDw==', private='YES', owner='default', country='UNITED ARAB EMIRATES', code='AE', x='2792', y='1222', area='83000', occupied='AE' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEoLEo06v9Le69IogrcITSCtACSJBeGIEe7pbCdS0l6CjEESxbU1kPtKWUZvd4m35tEsf91l8KTcGJn2/ENxQP3Q==', private='NO', owner='default', country='UNITED KINGDOM', code='GB', x='2119', y='694', area='243000', occupied='GB' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE8x++GRC5LQ1XH2sg0kbMQkGEwnmJFffK4qLFQLVpH7Avv2MIoI4L18w2/FwMMxIo14NKKJ4b4+tSM4ES60eTkQ==', private='NO', owner='default', country='UNITED STATES', code='US', x='1000', y='1000', area='9500000', occupied='US' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAETuMZA4y4/TRPWgBRAsSvVqTNtZMbe2jgWnXshznygWhBPTSd80239Q1lJ3LUYg/lK0PBqEpu+nsBuQeXHmXlGA==', private='YES', owner='default', country='URUGUAY', code='UY', x='1516', y='1924', area='176000', occupied='UY' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAET3zzONr9zzoOGYFQnyaJ+0Hemd7obh/0SCN0JfTJEVv/IhYt2/XP5PzeQyKGyJsqGCVtzwIfAzsh9luV0/YVIQ==', private='NO', owner='default', country='UZBEKISTAN', code='UZ', x='2878', y='950', area='447000', occupied='UZ' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEHVx9bYWll5xGRh6i6DvJ/I5A13l5IZMAAJRBWyrAKi6UzNoUfLYdevYRzf4O+Fz+2Yjig+nPFwdXYICp3XDiqg==', private='YES', owner='default', country='VANUATU', code='VU', x='4161', y='1700', area='12000', occupied='VU' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE6CMveXT90/EfFGHioDgmikt+tSM8a0lVEfKWcN8FKNgk8fsdjvdieEIXT0jJtI9ri3S4KC9EynAyoQRbN1Oaxg==', private='YES', owner='default', country='VATICAN CITY STATE', code='VA', x='2301', y='893', area='1', occupied='VA' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE5E+7kaf8WoPyWjmJ2fd+c2xfCcQLkRNc720jj6cH5BefBJ9Y7eAybNF+rJxfMqJm0d3QOFj8aWiQjDVPkG8iuQ==', private='NO', owner='default', country='VENEZUELA', code='VE', x='1376', y='1418', area='915000', occupied='VE' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEy/KPlJWYC9QJxLqb54SdkRZ+OBg4ZPFzaj+eIwcBC2NJVC0yLiUhzgSH7phMfz6FhLXm5TWE+p6T+TW71GPsFQ==', private='NO', owner='default', country='VIETNAM', code='VN', x='3416', y='1240', area='331000', occupied='VN' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEaZh7Hb508clSRz3W5MiRugZNWkfa41o+BJaHeXsYaOdsLgqzj8qErZNfTLLeFIRc2OtUXhF10zh++/5m5JM5aw==', private='YES', owner='default', country='WESTERN SAHARA', code='EH', x='2000', y='1200', area='266000', occupied='EH' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEwYZ3/xiTlQVgWT4ipBdg5Aj2hSqoi7Fvu22VBTPghmfGKFiLFvdtA8PDRTo4Clh6iFG/D0Pin8UAA92SXm/VkQ==', private='YES', owner='default', country='YEMEN', code='YE', x='2710', y='1317', area='527000', occupied='YE' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEYVWxgS5vo4IX6Q4Px9xpjVMXSccGr+oUniUm9znoRG9yvbgTVm7ScLPy0T+pIgYIKoTS4L1ZxIe03GYgSjoGhA==', private='YES', owner='default', country='ZAMBIA', code='ZM', x='2473', y='1687', area='750000', occupied='ZM' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEg2gm3JGklXZZ4oAe1DG8a6YvUK8EEOsQsZ3WmPHaH1YkA7ni/6WjkzpyC5bScFYPA2l6ZDquO1zTx8PZZI2AZA==', private='YES', owner='default', country='ZIMBABWE', code='ZW', x='2518', y='1738', area='390000', occupied='ZW' ");
        UTILS.DB.executeUpdate("INSERT INTO countries SET adr='MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAEnjhIEv1jVZMtZiO+WoTvFfU2gHo748+4DW9gVloCxBLHlzWEwSw6yB0HYWVBvx4RoNpGsG2y9MoL8W5DMQwTNQ==', private='YES', owner='default', country='MONTENEGRO', code='ME', x='2384', y='876', area='13000', occupied='ME' ");
}
}
